// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         provider_key: "provider_key"
 *     }
 */
export interface OauthCallbackOauthProviderKeyCallbackGetRequest {
    provider_key: string;
    code?: string | null;
    state?: string | null;
    error?: string | null;
    error_description?: string | null;
}
