// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         provider_key: "provider_key"
 *     }
 */
export interface ConnectCreateConnectionRequest {
    provider_key: string;
    external_id?: string | null;
    scopes?: string[] | null;
    redirect_uri?: string | null;
    credentials?: Record<string, string | null> | null;
}
