// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface CreateLinkTokenRequest {
    end_user_id?: string | null;
    allowed_providers?: string[] | null;
    redirect_uri?: string | null;
    ttl_seconds?: number | null;
    connection_id?: string | null;
}
