/* tslint:disable */
/* eslint-disable */
/**
 * Omnidapter Server
 * Self-hosted REST API wrapping the Omnidapter calendar integration library
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateCalendarRequest,
  CreateEventRequest,
  HTTPValidationError,
  UpdateCalendarRequest,
  UpdateEventRequest,
} from '../models/index';
import {
    CreateCalendarRequestFromJSON,
    CreateCalendarRequestToJSON,
    CreateEventRequestFromJSON,
    CreateEventRequestToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    UpdateCalendarRequestFromJSON,
    UpdateCalendarRequestToJSON,
    UpdateEventRequestFromJSON,
    UpdateEventRequestToJSON,
} from '../models/index';

export interface CreateCalendarOperationRequest {
    connectionId: string;
    createCalendarRequest: CreateCalendarRequest;
}

export interface CreateEventOperationRequest {
    connectionId: string;
    calendarId: string;
    createEventRequest: CreateEventRequest;
}

export interface DeleteCalendarRequest {
    connectionId: string;
    calendarId: string;
}

export interface DeleteEventRequest {
    connectionId: string;
    calendarId: string;
    eventId: string;
}

export interface GetAvailabilityRequest {
    connectionId: string;
    calendarId: string;
    start: Date;
    end: Date;
}

export interface GetCalendarRequest {
    connectionId: string;
    calendarId: string;
}

export interface GetEventRequest {
    connectionId: string;
    calendarId: string;
    eventId: string;
}

export interface ListCalendarsRequest {
    connectionId: string;
}

export interface ListEventsRequest {
    connectionId: string;
    calendarId: string;
    start?: Date | null;
    end?: Date | null;
    limit?: number;
    offset?: number;
}

export interface UpdateCalendarOperationRequest {
    connectionId: string;
    calendarId: string;
    updateCalendarRequest: UpdateCalendarRequest;
}

export interface UpdateEventOperationRequest {
    connectionId: string;
    calendarId: string;
    eventId: string;
    updateEventRequest: UpdateEventRequest;
}

/**
 * 
 */
export class CalendarApi extends runtime.BaseAPI {

    /**
     * Creates request options for createCalendar without sending the request
     */
    async createCalendarRequestOpts(requestParameters: CreateCalendarOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['connectionId'] == null) {
            throw new runtime.RequiredError(
                'connectionId',
                'Required parameter "connectionId" was null or undefined when calling createCalendar().'
            );
        }

        if (requestParameters['createCalendarRequest'] == null) {
            throw new runtime.RequiredError(
                'createCalendarRequest',
                'Required parameter "createCalendarRequest" was null or undefined when calling createCalendar().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("APIKeyAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/connections/{connection_id}/calendars`;
        urlPath = urlPath.replace('{connection_id}', encodeURIComponent(String(requestParameters['connectionId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateCalendarRequestToJSON(requestParameters['createCalendarRequest']),
        };
    }

    /**
     * Create Calendar
     */
    async createCalendarRaw(requestParameters: CreateCalendarOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.createCalendarRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Create Calendar
     */
    async createCalendar(requestParameters: CreateCalendarOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.createCalendarRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createEvent without sending the request
     */
    async createEventRequestOpts(requestParameters: CreateEventOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['connectionId'] == null) {
            throw new runtime.RequiredError(
                'connectionId',
                'Required parameter "connectionId" was null or undefined when calling createEvent().'
            );
        }

        if (requestParameters['calendarId'] == null) {
            throw new runtime.RequiredError(
                'calendarId',
                'Required parameter "calendarId" was null or undefined when calling createEvent().'
            );
        }

        if (requestParameters['createEventRequest'] == null) {
            throw new runtime.RequiredError(
                'createEventRequest',
                'Required parameter "createEventRequest" was null or undefined when calling createEvent().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("APIKeyAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/connections/{connection_id}/calendars/{calendar_id}/events`;
        urlPath = urlPath.replace('{connection_id}', encodeURIComponent(String(requestParameters['connectionId'])));
        urlPath = urlPath.replace('{calendar_id}', encodeURIComponent(String(requestParameters['calendarId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateEventRequestToJSON(requestParameters['createEventRequest']),
        };
    }

    /**
     * Create Event
     */
    async createEventRaw(requestParameters: CreateEventOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.createEventRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Create Event
     */
    async createEvent(requestParameters: CreateEventOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.createEventRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteCalendar without sending the request
     */
    async deleteCalendarRequestOpts(requestParameters: DeleteCalendarRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['connectionId'] == null) {
            throw new runtime.RequiredError(
                'connectionId',
                'Required parameter "connectionId" was null or undefined when calling deleteCalendar().'
            );
        }

        if (requestParameters['calendarId'] == null) {
            throw new runtime.RequiredError(
                'calendarId',
                'Required parameter "calendarId" was null or undefined when calling deleteCalendar().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("APIKeyAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/connections/{connection_id}/calendars/{calendar_id}`;
        urlPath = urlPath.replace('{connection_id}', encodeURIComponent(String(requestParameters['connectionId'])));
        urlPath = urlPath.replace('{calendar_id}', encodeURIComponent(String(requestParameters['calendarId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete Calendar
     */
    async deleteCalendarRaw(requestParameters: DeleteCalendarRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteCalendarRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete Calendar
     */
    async deleteCalendar(requestParameters: DeleteCalendarRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteCalendarRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for deleteEvent without sending the request
     */
    async deleteEventRequestOpts(requestParameters: DeleteEventRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['connectionId'] == null) {
            throw new runtime.RequiredError(
                'connectionId',
                'Required parameter "connectionId" was null or undefined when calling deleteEvent().'
            );
        }

        if (requestParameters['calendarId'] == null) {
            throw new runtime.RequiredError(
                'calendarId',
                'Required parameter "calendarId" was null or undefined when calling deleteEvent().'
            );
        }

        if (requestParameters['eventId'] == null) {
            throw new runtime.RequiredError(
                'eventId',
                'Required parameter "eventId" was null or undefined when calling deleteEvent().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("APIKeyAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/connections/{connection_id}/calendars/{calendar_id}/events/{event_id}`;
        urlPath = urlPath.replace('{connection_id}', encodeURIComponent(String(requestParameters['connectionId'])));
        urlPath = urlPath.replace('{calendar_id}', encodeURIComponent(String(requestParameters['calendarId'])));
        urlPath = urlPath.replace('{event_id}', encodeURIComponent(String(requestParameters['eventId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete Event
     */
    async deleteEventRaw(requestParameters: DeleteEventRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteEventRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete Event
     */
    async deleteEvent(requestParameters: DeleteEventRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteEventRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getAvailability without sending the request
     */
    async getAvailabilityRequestOpts(requestParameters: GetAvailabilityRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['connectionId'] == null) {
            throw new runtime.RequiredError(
                'connectionId',
                'Required parameter "connectionId" was null or undefined when calling getAvailability().'
            );
        }

        if (requestParameters['calendarId'] == null) {
            throw new runtime.RequiredError(
                'calendarId',
                'Required parameter "calendarId" was null or undefined when calling getAvailability().'
            );
        }

        if (requestParameters['start'] == null) {
            throw new runtime.RequiredError(
                'start',
                'Required parameter "start" was null or undefined when calling getAvailability().'
            );
        }

        if (requestParameters['end'] == null) {
            throw new runtime.RequiredError(
                'end',
                'Required parameter "end" was null or undefined when calling getAvailability().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['start'] != null) {
            queryParameters['start'] = (requestParameters['start'] as any).toISOString();
        }

        if (requestParameters['end'] != null) {
            queryParameters['end'] = (requestParameters['end'] as any).toISOString();
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("APIKeyAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/connections/{connection_id}/calendars/{calendar_id}/availability`;
        urlPath = urlPath.replace('{connection_id}', encodeURIComponent(String(requestParameters['connectionId'])));
        urlPath = urlPath.replace('{calendar_id}', encodeURIComponent(String(requestParameters['calendarId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Availability
     */
    async getAvailabilityRaw(requestParameters: GetAvailabilityRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.getAvailabilityRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Get Availability
     */
    async getAvailability(requestParameters: GetAvailabilityRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.getAvailabilityRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getCalendar without sending the request
     */
    async getCalendarRequestOpts(requestParameters: GetCalendarRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['connectionId'] == null) {
            throw new runtime.RequiredError(
                'connectionId',
                'Required parameter "connectionId" was null or undefined when calling getCalendar().'
            );
        }

        if (requestParameters['calendarId'] == null) {
            throw new runtime.RequiredError(
                'calendarId',
                'Required parameter "calendarId" was null or undefined when calling getCalendar().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("APIKeyAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/connections/{connection_id}/calendars/{calendar_id}`;
        urlPath = urlPath.replace('{connection_id}', encodeURIComponent(String(requestParameters['connectionId'])));
        urlPath = urlPath.replace('{calendar_id}', encodeURIComponent(String(requestParameters['calendarId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Calendar
     */
    async getCalendarRaw(requestParameters: GetCalendarRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.getCalendarRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Get Calendar
     */
    async getCalendar(requestParameters: GetCalendarRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.getCalendarRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getEvent without sending the request
     */
    async getEventRequestOpts(requestParameters: GetEventRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['connectionId'] == null) {
            throw new runtime.RequiredError(
                'connectionId',
                'Required parameter "connectionId" was null or undefined when calling getEvent().'
            );
        }

        if (requestParameters['calendarId'] == null) {
            throw new runtime.RequiredError(
                'calendarId',
                'Required parameter "calendarId" was null or undefined when calling getEvent().'
            );
        }

        if (requestParameters['eventId'] == null) {
            throw new runtime.RequiredError(
                'eventId',
                'Required parameter "eventId" was null or undefined when calling getEvent().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("APIKeyAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/connections/{connection_id}/calendars/{calendar_id}/events/{event_id}`;
        urlPath = urlPath.replace('{connection_id}', encodeURIComponent(String(requestParameters['connectionId'])));
        urlPath = urlPath.replace('{calendar_id}', encodeURIComponent(String(requestParameters['calendarId'])));
        urlPath = urlPath.replace('{event_id}', encodeURIComponent(String(requestParameters['eventId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Event
     */
    async getEventRaw(requestParameters: GetEventRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.getEventRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Get Event
     */
    async getEvent(requestParameters: GetEventRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.getEventRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listCalendars without sending the request
     */
    async listCalendarsRequestOpts(requestParameters: ListCalendarsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['connectionId'] == null) {
            throw new runtime.RequiredError(
                'connectionId',
                'Required parameter "connectionId" was null or undefined when calling listCalendars().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("APIKeyAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/connections/{connection_id}/calendars`;
        urlPath = urlPath.replace('{connection_id}', encodeURIComponent(String(requestParameters['connectionId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List Calendars
     */
    async listCalendarsRaw(requestParameters: ListCalendarsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.listCalendarsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * List Calendars
     */
    async listCalendars(requestParameters: ListCalendarsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.listCalendarsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listEvents without sending the request
     */
    async listEventsRequestOpts(requestParameters: ListEventsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['connectionId'] == null) {
            throw new runtime.RequiredError(
                'connectionId',
                'Required parameter "connectionId" was null or undefined when calling listEvents().'
            );
        }

        if (requestParameters['calendarId'] == null) {
            throw new runtime.RequiredError(
                'calendarId',
                'Required parameter "calendarId" was null or undefined when calling listEvents().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['start'] != null) {
            queryParameters['start'] = (requestParameters['start'] as any).toISOString();
        }

        if (requestParameters['end'] != null) {
            queryParameters['end'] = (requestParameters['end'] as any).toISOString();
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("APIKeyAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/connections/{connection_id}/calendars/{calendar_id}/events`;
        urlPath = urlPath.replace('{connection_id}', encodeURIComponent(String(requestParameters['connectionId'])));
        urlPath = urlPath.replace('{calendar_id}', encodeURIComponent(String(requestParameters['calendarId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List Events
     */
    async listEventsRaw(requestParameters: ListEventsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.listEventsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * List Events
     */
    async listEvents(requestParameters: ListEventsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.listEventsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateCalendar without sending the request
     */
    async updateCalendarRequestOpts(requestParameters: UpdateCalendarOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['connectionId'] == null) {
            throw new runtime.RequiredError(
                'connectionId',
                'Required parameter "connectionId" was null or undefined when calling updateCalendar().'
            );
        }

        if (requestParameters['calendarId'] == null) {
            throw new runtime.RequiredError(
                'calendarId',
                'Required parameter "calendarId" was null or undefined when calling updateCalendar().'
            );
        }

        if (requestParameters['updateCalendarRequest'] == null) {
            throw new runtime.RequiredError(
                'updateCalendarRequest',
                'Required parameter "updateCalendarRequest" was null or undefined when calling updateCalendar().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("APIKeyAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/connections/{connection_id}/calendars/{calendar_id}`;
        urlPath = urlPath.replace('{connection_id}', encodeURIComponent(String(requestParameters['connectionId'])));
        urlPath = urlPath.replace('{calendar_id}', encodeURIComponent(String(requestParameters['calendarId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateCalendarRequestToJSON(requestParameters['updateCalendarRequest']),
        };
    }

    /**
     * Update Calendar
     */
    async updateCalendarRaw(requestParameters: UpdateCalendarOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.updateCalendarRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Update Calendar
     */
    async updateCalendar(requestParameters: UpdateCalendarOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.updateCalendarRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateEvent without sending the request
     */
    async updateEventRequestOpts(requestParameters: UpdateEventOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['connectionId'] == null) {
            throw new runtime.RequiredError(
                'connectionId',
                'Required parameter "connectionId" was null or undefined when calling updateEvent().'
            );
        }

        if (requestParameters['calendarId'] == null) {
            throw new runtime.RequiredError(
                'calendarId',
                'Required parameter "calendarId" was null or undefined when calling updateEvent().'
            );
        }

        if (requestParameters['eventId'] == null) {
            throw new runtime.RequiredError(
                'eventId',
                'Required parameter "eventId" was null or undefined when calling updateEvent().'
            );
        }

        if (requestParameters['updateEventRequest'] == null) {
            throw new runtime.RequiredError(
                'updateEventRequest',
                'Required parameter "updateEventRequest" was null or undefined when calling updateEvent().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("APIKeyAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/connections/{connection_id}/calendars/{calendar_id}/events/{event_id}`;
        urlPath = urlPath.replace('{connection_id}', encodeURIComponent(String(requestParameters['connectionId'])));
        urlPath = urlPath.replace('{calendar_id}', encodeURIComponent(String(requestParameters['calendarId'])));
        urlPath = urlPath.replace('{event_id}', encodeURIComponent(String(requestParameters['eventId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateEventRequestToJSON(requestParameters['updateEventRequest']),
        };
    }

    /**
     * Update Event
     */
    async updateEventRaw(requestParameters: UpdateEventOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.updateEventRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Update Event
     */
    async updateEvent(requestParameters: UpdateEventOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.updateEventRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
