/* tslint:disable */
/* eslint-disable */
/**
 * Omnidapter Server
 * Self-hosted REST API wrapping the Omnidapter calendar integration library
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateLinkTokenRequest,
  HTTPValidationError,
} from '../models/index';
import {
    CreateLinkTokenRequestFromJSON,
    CreateLinkTokenRequestToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/index';

export interface CreateLinkTokenOperationRequest {
    createLinkTokenRequest: CreateLinkTokenRequest;
}

/**
 * 
 */
export class LinkTokensApi extends runtime.BaseAPI {

    /**
     * Creates request options for createLinkToken without sending the request
     */
    async createLinkTokenRequestOpts(requestParameters: CreateLinkTokenOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createLinkTokenRequest'] == null) {
            throw new runtime.RequiredError(
                'createLinkTokenRequest',
                'Required parameter "createLinkTokenRequest" was null or undefined when calling createLinkToken().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("APIKeyAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/link-tokens`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateLinkTokenRequestToJSON(requestParameters['createLinkTokenRequest']),
        };
    }

    /**
     * Create a short-lived link token for the Connect UI.  Pass the returned token to the embedded or redirect Connect UI as a Bearer token. The token grants permission to list providers and initiate a connection, optionally scoped to ``end_user_id``.  Set ``connection_id`` to create a *reconnect* token — the connect UI will skip provider selection and go directly to the authorization flow for the existing connection.
     * Create Link Token Endpoint
     */
    async createLinkTokenRaw(requestParameters: CreateLinkTokenOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.createLinkTokenRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Create a short-lived link token for the Connect UI.  Pass the returned token to the embedded or redirect Connect UI as a Bearer token. The token grants permission to list providers and initiate a connection, optionally scoped to ``end_user_id``.  Set ``connection_id`` to create a *reconnect* token — the connect UI will skip provider selection and go directly to the authorization flow for the existing connection.
     * Create Link Token Endpoint
     */
    async createLinkToken(requestParameters: CreateLinkTokenOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.createLinkTokenRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
