# This file was auto-generated by Fern from our API Definition.

from omnidapter_sdk import OmnidapterApi
from omnidapter_sdk import AsyncOmnidapterApi
import typing
from .utilities import validate_response


async def test_create_session(
    client: OmnidapterApi, async_client: AsyncOmnidapterApi
) -> None:
    expected_response: typing.Any = {"key": "value"}
    expected_types: typing.Tuple[typing.Any, typing.Any] = ("dict", {0: (None, None)})
    response = client.connect.create_session(token="token")
    validate_response(response, expected_response, expected_types)

    async_response = await async_client.connect.create_session(token="token")
    validate_response(async_response, expected_response, expected_types)


async def test_list_providers(
    client: OmnidapterApi, async_client: AsyncOmnidapterApi
) -> None:
    expected_response: typing.Any = {"key": "value"}
    expected_types: typing.Any = None
    response = client.connect.list_providers()
    validate_response(response, expected_response, expected_types)

    async_response = await async_client.connect.list_providers()
    validate_response(async_response, expected_response, expected_types)


async def test_create_connection(
    client: OmnidapterApi, async_client: AsyncOmnidapterApi
) -> None:
    expected_response: typing.Any = {"key": "value"}
    expected_types: typing.Any = None
    response = client.connect.create_connection(provider_key="provider_key")
    validate_response(response, expected_response, expected_types)

    async_response = await async_client.connect.create_connection(
        provider_key="provider_key"
    )
    validate_response(async_response, expected_response, expected_types)
