# This file was auto-generated by Fern from our API Definition.

from omnidapter_sdk import OmnidapterApi
from omnidapter_sdk import AsyncOmnidapterApi
import typing
from .utilities import validate_response
import datetime


async def test_list_calendars(client: OmnidapterApi, async_client: AsyncOmnidapterApi) -> None:
    expected_response: typing.Any = {"key": "value"}
    expected_types: typing.Any = None
    response = client.calendar.list_calendars(connection_id="connection_id")
    validate_response(response, expected_response, expected_types)

    async_response = await async_client.calendar.list_calendars(connection_id="connection_id")
    validate_response(async_response, expected_response, expected_types)


async def test_create_calendar(client: OmnidapterApi, async_client: AsyncOmnidapterApi) -> None:
    expected_response: typing.Any = {"key": "value"}
    expected_types: typing.Any = None
    response = client.calendar.create_calendar(connection_id="connection_id", summary="summary")
    validate_response(response, expected_response, expected_types)

    async_response = await async_client.calendar.create_calendar(
        connection_id="connection_id", summary="summary"
    )
    validate_response(async_response, expected_response, expected_types)


async def test_get_calendar(client: OmnidapterApi, async_client: AsyncOmnidapterApi) -> None:
    expected_response: typing.Any = {"key": "value"}
    expected_types: typing.Any = None
    response = client.calendar.get_calendar(
        connection_id="connection_id", calendar_id="calendar_id"
    )
    validate_response(response, expected_response, expected_types)

    async_response = await async_client.calendar.get_calendar(
        connection_id="connection_id", calendar_id="calendar_id"
    )
    validate_response(async_response, expected_response, expected_types)


async def test_delete_calendar(client: OmnidapterApi, async_client: AsyncOmnidapterApi) -> None:
    # Type ignore to avoid mypy complaining about the function not being meant to return a value
    assert (
        client.calendar.delete_calendar(connection_id="connection_id", calendar_id="calendar_id")  # type: ignore[func-returns-value]
        is None
    )

    assert (
        await async_client.calendar.delete_calendar(
            connection_id="connection_id", calendar_id="calendar_id"
        )  # type: ignore[func-returns-value]
        is None
    )


async def test_update_calendar(client: OmnidapterApi, async_client: AsyncOmnidapterApi) -> None:
    expected_response: typing.Any = {"key": "value"}
    expected_types: typing.Any = None
    response = client.calendar.update_calendar(
        connection_id="connection_id", calendar_id="calendar_id"
    )
    validate_response(response, expected_response, expected_types)

    async_response = await async_client.calendar.update_calendar(
        connection_id="connection_id", calendar_id="calendar_id"
    )
    validate_response(async_response, expected_response, expected_types)


async def test_list_events(client: OmnidapterApi, async_client: AsyncOmnidapterApi) -> None:
    expected_response: typing.Any = {"key": "value"}
    expected_types: typing.Any = None
    response = client.calendar.list_events(connection_id="connection_id", calendar_id="calendar_id")
    validate_response(response, expected_response, expected_types)

    async_response = await async_client.calendar.list_events(
        connection_id="connection_id", calendar_id="calendar_id"
    )
    validate_response(async_response, expected_response, expected_types)


async def test_create_event(client: OmnidapterApi, async_client: AsyncOmnidapterApi) -> None:
    expected_response: typing.Any = {"key": "value"}
    expected_types: typing.Any = None
    response = client.calendar.create_event(
        connection_id="connection_id",
        calendar_id="calendar_id",
        summary="summary",
        start=datetime.datetime.fromisoformat("2024-01-15 09:30:00+00:00"),
        end=datetime.datetime.fromisoformat("2024-01-15 09:30:00+00:00"),
    )
    validate_response(response, expected_response, expected_types)

    async_response = await async_client.calendar.create_event(
        connection_id="connection_id",
        calendar_id="calendar_id",
        summary="summary",
        start=datetime.datetime.fromisoformat("2024-01-15 09:30:00+00:00"),
        end=datetime.datetime.fromisoformat("2024-01-15 09:30:00+00:00"),
    )
    validate_response(async_response, expected_response, expected_types)


async def test_get_event(client: OmnidapterApi, async_client: AsyncOmnidapterApi) -> None:
    expected_response: typing.Any = {"key": "value"}
    expected_types: typing.Any = None
    response = client.calendar.get_event(
        connection_id="connection_id", calendar_id="calendar_id", event_id="event_id"
    )
    validate_response(response, expected_response, expected_types)

    async_response = await async_client.calendar.get_event(
        connection_id="connection_id", calendar_id="calendar_id", event_id="event_id"
    )
    validate_response(async_response, expected_response, expected_types)


async def test_delete_event(client: OmnidapterApi, async_client: AsyncOmnidapterApi) -> None:
    # Type ignore to avoid mypy complaining about the function not being meant to return a value
    assert (
        client.calendar.delete_event(
            connection_id="connection_id",
            calendar_id="calendar_id",
            event_id="event_id",
        )  # type: ignore[func-returns-value]
        is None
    )

    assert (
        await async_client.calendar.delete_event(
            connection_id="connection_id",
            calendar_id="calendar_id",
            event_id="event_id",
        )  # type: ignore[func-returns-value]
        is None
    )


async def test_update_event(client: OmnidapterApi, async_client: AsyncOmnidapterApi) -> None:
    expected_response: typing.Any = {"key": "value"}
    expected_types: typing.Any = None
    response = client.calendar.update_event(
        connection_id="connection_id", calendar_id="calendar_id", event_id="event_id"
    )
    validate_response(response, expected_response, expected_types)

    async_response = await async_client.calendar.update_event(
        connection_id="connection_id", calendar_id="calendar_id", event_id="event_id"
    )
    validate_response(async_response, expected_response, expected_types)


async def test_get_availability(client: OmnidapterApi, async_client: AsyncOmnidapterApi) -> None:
    expected_response: typing.Any = {"key": "value"}
    expected_types: typing.Any = None
    response = client.calendar.get_availability(
        connection_id="connection_id",
        calendar_id="calendar_id",
        start=datetime.datetime.fromisoformat("2024-01-15 09:30:00+00:00"),
        end=datetime.datetime.fromisoformat("2024-01-15 09:30:00+00:00"),
    )
    validate_response(response, expected_response, expected_types)

    async_response = await async_client.calendar.get_availability(
        connection_id="connection_id",
        calendar_id="calendar_id",
        start=datetime.datetime.fromisoformat("2024-01-15 09:30:00+00:00"),
        end=datetime.datetime.fromisoformat("2024-01-15 09:30:00+00:00"),
    )
    validate_response(async_response, expected_response, expected_types)
