# This file was auto-generated by Fern from our API Definition.

from omnidapter_sdk import OmnidapterApi
from omnidapter_sdk import AsyncOmnidapterApi
import typing
from .utilities import validate_response


async def test_list_connections(
    client: OmnidapterApi, async_client: AsyncOmnidapterApi
) -> None:
    expected_response: typing.Any = {"key": "value"}
    expected_types: typing.Any = None
    response = client.connections.list_connections()
    validate_response(response, expected_response, expected_types)

    async_response = await async_client.connections.list_connections()
    validate_response(async_response, expected_response, expected_types)


async def test_create_connection(
    client: OmnidapterApi, async_client: AsyncOmnidapterApi
) -> None:
    expected_response: typing.Any = {"key": "value"}
    expected_types: typing.Any = None
    response = client.connections.create_connection(
        provider="provider", redirect_url="redirect_url"
    )
    validate_response(response, expected_response, expected_types)

    async_response = await async_client.connections.create_connection(
        provider="provider", redirect_url="redirect_url"
    )
    validate_response(async_response, expected_response, expected_types)


async def test_get_connection_endpoint(
    client: OmnidapterApi, async_client: AsyncOmnidapterApi
) -> None:
    expected_response: typing.Any = {"key": "value"}
    expected_types: typing.Any = None
    response = client.connections.get_connection_endpoint(connection_id="connection_id")
    validate_response(response, expected_response, expected_types)

    async_response = await async_client.connections.get_connection_endpoint(
        connection_id="connection_id"
    )
    validate_response(async_response, expected_response, expected_types)


async def test_delete_connection(
    client: OmnidapterApi, async_client: AsyncOmnidapterApi
) -> None:
    # Type ignore to avoid mypy complaining about the function not being meant to return a value
    assert (
        client.connections.delete_connection(connection_id="connection_id")  # type: ignore[func-returns-value]
        is None
    )

    assert (
        await async_client.connections.delete_connection(connection_id="connection_id")  # type: ignore[func-returns-value]
        is None
    )


async def test_reauthorize_connection(
    client: OmnidapterApi, async_client: AsyncOmnidapterApi
) -> None:
    expected_response: typing.Any = {"key": "value"}
    expected_types: typing.Any = None
    response = client.connections.reauthorize_connection(
        connection_id="connection_id", redirect_url="redirect_url"
    )
    validate_response(response, expected_response, expected_types)

    async_response = await async_client.connections.reauthorize_connection(
        connection_id="connection_id", redirect_url="redirect_url"
    )
    validate_response(async_response, expected_response, expected_types)
