# This file was auto-generated by Fern from our API Definition.

from omnidapter_sdk import OmnidapterApi
from omnidapter_sdk import AsyncOmnidapterApi
import typing
from .utilities import validate_response


async def test_get_profile(
    client: OmnidapterApi, async_client: AsyncOmnidapterApi
) -> None:
    expected_response: typing.Any = {"key": "value"}
    expected_types: typing.Any = None
    response = client.dashboard.get_profile()
    validate_response(response, expected_response, expected_types)

    async_response = await async_client.dashboard.get_profile()
    validate_response(async_response, expected_response, expected_types)


async def test_update_profile(
    client: OmnidapterApi, async_client: AsyncOmnidapterApi
) -> None:
    expected_response: typing.Any = {"key": "value"}
    expected_types: typing.Any = None
    response = client.dashboard.update_profile(name="name")
    validate_response(response, expected_response, expected_types)

    async_response = await async_client.dashboard.update_profile(name="name")
    validate_response(async_response, expected_response, expected_types)


async def test_get_tenant(
    client: OmnidapterApi, async_client: AsyncOmnidapterApi
) -> None:
    expected_response: typing.Any = {"key": "value"}
    expected_types: typing.Any = None
    response = client.dashboard.get_tenant()
    validate_response(response, expected_response, expected_types)

    async_response = await async_client.dashboard.get_tenant()
    validate_response(async_response, expected_response, expected_types)


async def test_patch_tenant(
    client: OmnidapterApi, async_client: AsyncOmnidapterApi
) -> None:
    expected_response: typing.Any = {"key": "value"}
    expected_types: typing.Any = None
    response = client.dashboard.patch_tenant(name="name")
    validate_response(response, expected_response, expected_types)

    async_response = await async_client.dashboard.patch_tenant(name="name")
    validate_response(async_response, expected_response, expected_types)


async def test_get_members(
    client: OmnidapterApi, async_client: AsyncOmnidapterApi
) -> None:
    expected_response: typing.Any = {"key": "value"}
    expected_types: typing.Any = None
    response = client.dashboard.get_members()
    validate_response(response, expected_response, expected_types)

    async_response = await async_client.dashboard.get_members()
    validate_response(async_response, expected_response, expected_types)


async def test_delete_member(
    client: OmnidapterApi, async_client: AsyncOmnidapterApi
) -> None:
    # Type ignore to avoid mypy complaining about the function not being meant to return a value
    assert (
        client.dashboard.delete_member(user_id="user_id")  # type: ignore[func-returns-value]
        is None
    )

    assert (
        await async_client.dashboard.delete_member(user_id="user_id")  # type: ignore[func-returns-value]
        is None
    )


async def test_list_api_keys(
    client: OmnidapterApi, async_client: AsyncOmnidapterApi
) -> None:
    expected_response: typing.Any = {"key": "value"}
    expected_types: typing.Any = None
    response = client.dashboard.list_api_keys()
    validate_response(response, expected_response, expected_types)

    async_response = await async_client.dashboard.list_api_keys()
    validate_response(async_response, expected_response, expected_types)


async def test_create_api_key(
    client: OmnidapterApi, async_client: AsyncOmnidapterApi
) -> None:
    expected_response: typing.Any = {"key": "value"}
    expected_types: typing.Any = None
    response = client.dashboard.create_api_key(name="name")
    validate_response(response, expected_response, expected_types)

    async_response = await async_client.dashboard.create_api_key(name="name")
    validate_response(async_response, expected_response, expected_types)


async def test_revoke_api_key(
    client: OmnidapterApi, async_client: AsyncOmnidapterApi
) -> None:
    # Type ignore to avoid mypy complaining about the function not being meant to return a value
    assert (
        client.dashboard.revoke_api_key(key_id="key_id")  # type: ignore[func-returns-value]
        is None
    )

    assert (
        await async_client.dashboard.revoke_api_key(key_id="key_id")  # type: ignore[func-returns-value]
        is None
    )


async def test_list_connections(
    client: OmnidapterApi, async_client: AsyncOmnidapterApi
) -> None:
    expected_response: typing.Any = {"key": "value"}
    expected_types: typing.Any = None
    response = client.dashboard.list_connections()
    validate_response(response, expected_response, expected_types)

    async_response = await async_client.dashboard.list_connections()
    validate_response(async_response, expected_response, expected_types)


async def test_revoke_connection(
    client: OmnidapterApi, async_client: AsyncOmnidapterApi
) -> None:
    # Type ignore to avoid mypy complaining about the function not being meant to return a value
    assert (
        client.dashboard.revoke_connection(connection_id="connection_id")  # type: ignore[func-returns-value]
        is None
    )

    assert (
        await async_client.dashboard.revoke_connection(connection_id="connection_id")  # type: ignore[func-returns-value]
        is None
    )


async def test_list_provider_configs(
    client: OmnidapterApi, async_client: AsyncOmnidapterApi
) -> None:
    expected_response: typing.Any = {"key": "value"}
    expected_types: typing.Any = None
    response = client.dashboard.list_provider_configs()
    validate_response(response, expected_response, expected_types)

    async_response = await async_client.dashboard.list_provider_configs()
    validate_response(async_response, expected_response, expected_types)


async def test_upsert_provider_config(
    client: OmnidapterApi, async_client: AsyncOmnidapterApi
) -> None:
    expected_response: typing.Any = {"key": "value"}
    expected_types: typing.Any = None
    response = client.dashboard.upsert_provider_config(
        provider_key="provider_key",
        client_id="client_id",
        client_secret="client_secret",
    )
    validate_response(response, expected_response, expected_types)

    async_response = await async_client.dashboard.upsert_provider_config(
        provider_key="provider_key",
        client_id="client_id",
        client_secret="client_secret",
    )
    validate_response(async_response, expected_response, expected_types)


async def test_delete_provider_config(
    client: OmnidapterApi, async_client: AsyncOmnidapterApi
) -> None:
    # Type ignore to avoid mypy complaining about the function not being meant to return a value
    assert (
        client.dashboard.delete_provider_config(provider_key="provider_key")  # type: ignore[func-returns-value]
        is None
    )

    assert (
        await async_client.dashboard.delete_provider_config(provider_key="provider_key")  # type: ignore[func-returns-value]
        is None
    )


async def test_get_usage(
    client: OmnidapterApi, async_client: AsyncOmnidapterApi
) -> None:
    expected_response: typing.Any = {"key": "value"}
    expected_types: typing.Any = None
    response = client.dashboard.get_usage()
    validate_response(response, expected_response, expected_types)

    async_response = await async_client.dashboard.get_usage()
    validate_response(async_response, expected_response, expected_types)
