# This file was auto-generated by Fern from our API Definition.

from omnidapter_sdk import OmnidapterApi
from omnidapter_sdk import AsyncOmnidapterApi
import typing
from .utilities import validate_response


async def test_oauth_callback(client: OmnidapterApi, async_client: AsyncOmnidapterApi) -> None:
    expected_response: typing.Any = {"key": "value"}
    expected_types: typing.Any = None
    response = client.oauth.oauth_callback(provider_key="provider_key")
    validate_response(response, expected_response, expected_types)

    async_response = await async_client.oauth.oauth_callback(provider_key="provider_key")
    validate_response(async_response, expected_response, expected_types)
