# This file was auto-generated by Fern from our API Definition.

from omnidapter_sdk import OmnidapterApi
from omnidapter_sdk import AsyncOmnidapterApi
import typing
from .utilities import validate_response


async def test_list_provider_configs(
    client: OmnidapterApi, async_client: AsyncOmnidapterApi
) -> None:
    expected_response: typing.Any = {"key": "value"}
    expected_types: typing.Any = None
    response = client.provider_configs.list_provider_configs()
    validate_response(response, expected_response, expected_types)

    async_response = await async_client.provider_configs.list_provider_configs()
    validate_response(async_response, expected_response, expected_types)


async def test_get_provider_config(client: OmnidapterApi, async_client: AsyncOmnidapterApi) -> None:
    expected_response: typing.Any = {"key": "value"}
    expected_types: typing.Any = None
    response = client.provider_configs.get_provider_config(provider_key="provider_key")
    validate_response(response, expected_response, expected_types)

    async_response = await async_client.provider_configs.get_provider_config(
        provider_key="provider_key"
    )
    validate_response(async_response, expected_response, expected_types)


async def test_upsert_provider_config(
    client: OmnidapterApi, async_client: AsyncOmnidapterApi
) -> None:
    expected_response: typing.Any = {"key": "value"}
    expected_types: typing.Any = None
    response = client.provider_configs.upsert_provider_config(
        provider_key="provider_key",
        client_id="client_id",
        client_secret="client_secret",
    )
    validate_response(response, expected_response, expected_types)

    async_response = await async_client.provider_configs.upsert_provider_config(
        provider_key="provider_key",
        client_id="client_id",
        client_secret="client_secret",
    )
    validate_response(async_response, expected_response, expected_types)


async def test_delete_provider_config(
    client: OmnidapterApi, async_client: AsyncOmnidapterApi
) -> None:
    # Type ignore to avoid mypy complaining about the function not being meant to return a value
    assert (
        client.provider_configs.delete_provider_config(provider_key="provider_key")  # type: ignore[func-returns-value]
        is None
    )

    assert (
        await async_client.provider_configs.delete_provider_config(provider_key="provider_key")  # type: ignore[func-returns-value]
        is None
    )


async def test_patch_provider_config(
    client: OmnidapterApi, async_client: AsyncOmnidapterApi
) -> None:
    expected_response: typing.Any = {"key": "value"}
    expected_types: typing.Any = None
    response = client.provider_configs.patch_provider_config(
        provider_key="provider_key", is_enabled=True
    )
    validate_response(response, expected_response, expected_types)

    async_response = await async_client.provider_configs.patch_provider_config(
        provider_key="provider_key", is_enabled=True
    )
    validate_response(async_response, expected_response, expected_types)
