from __future__ import annotations

from collections.abc import AsyncIterator
from typing import Protocol

from omnidapter.services.calendar.models import AvailabilityResponse, Calendar, Event, EventUpsertRequest
from omnidapter.services.calendar.pagination import PaginatedResult


class CalendarService(Protocol):
    async def list_calendars(self) -> list[Calendar]: ...

    async def get_availability(self, calendar_id: str) -> AvailabilityResponse: ...

    async def create_event(self, payload: EventUpsertRequest) -> Event: ...

    async def update_event(self, event_id: str, payload: EventUpsertRequest) -> Event: ...

    async def delete_event(self, event_id: str) -> None: ...

    async def get_event(self, event_id: str) -> Event: ...

    async def list_events_page(self, calendar_id: str, page_token: str | None = None) -> PaginatedResult[Event]: ...

    async def list_events(self, calendar_id: str) -> AsyncIterator[Event]: ...
