/* tslint:disable */
/* eslint-disable */
/**
 * Omnidapter Server
 * Self-hosted REST API wrapping the Omnidapter calendar integration library
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AttendeeStatus } from './AttendeeStatus';
import {
    AttendeeStatusFromJSON,
    AttendeeStatusFromJSONTyped,
    AttendeeStatusToJSON,
    AttendeeStatusToJSONTyped,
} from './AttendeeStatus';

/**
 * An event attendee.
 * @export
 * @interface Attendee
 */
export interface Attendee {
    /**
     * 
     * @type {string}
     * @memberof Attendee
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof Attendee
     */
    displayName?: string | null;
    /**
     * 
     * @type {AttendeeStatus}
     * @memberof Attendee
     */
    status?: AttendeeStatus;
    /**
     * 
     * @type {boolean}
     * @memberof Attendee
     */
    isOrganizer?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Attendee
     */
    isSelf?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Attendee
     */
    isResource?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Attendee
     */
    optional?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Attendee
     */
    comment?: string | null;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof Attendee
     */
    providerData?: { [key: string]: any; } | null;
}



/**
 * Check if a given object implements the Attendee interface.
 */
export function instanceOfAttendee(value: object): value is Attendee {
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function AttendeeFromJSON(json: any): Attendee {
    return AttendeeFromJSONTyped(json, false);
}

export function AttendeeFromJSONTyped(json: any, ignoreDiscriminator: boolean): Attendee {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'displayName': json['display_name'] == null ? undefined : json['display_name'],
        'status': json['status'] == null ? undefined : AttendeeStatusFromJSON(json['status']),
        'isOrganizer': json['is_organizer'] == null ? undefined : json['is_organizer'],
        'isSelf': json['is_self'] == null ? undefined : json['is_self'],
        'isResource': json['is_resource'] == null ? undefined : json['is_resource'],
        'optional': json['optional'] == null ? undefined : json['optional'],
        'comment': json['comment'] == null ? undefined : json['comment'],
        'providerData': json['provider_data'] == null ? undefined : json['provider_data'],
    };
}

export function AttendeeToJSON(json: any): Attendee {
    return AttendeeToJSONTyped(json, false);
}

export function AttendeeToJSONTyped(value?: Attendee | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'display_name': value['displayName'],
        'status': AttendeeStatusToJSON(value['status']),
        'is_organizer': value['isOrganizer'],
        'is_self': value['isSelf'],
        'is_resource': value['isResource'],
        'optional': value['optional'],
        'comment': value['comment'],
        'provider_data': value['providerData'],
    };
}

