/* tslint:disable */
/* eslint-disable */
/**
 * Omnidapter Server
 * Self-hosted REST API wrapping the Omnidapter calendar integration library
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const AttendeeStatus = {
    Accepted: 'accepted',
    Declined: 'declined',
    Tentative: 'tentative',
    NeedsAction: 'needs_action',
    Unknown: 'unknown'
} as const;
export type AttendeeStatus = typeof AttendeeStatus[keyof typeof AttendeeStatus];


export function instanceOfAttendeeStatus(value: any): boolean {
    for (const key in AttendeeStatus) {
        if (Object.prototype.hasOwnProperty.call(AttendeeStatus, key)) {
            if (AttendeeStatus[key as keyof typeof AttendeeStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function AttendeeStatusFromJSON(json: any): AttendeeStatus {
    return AttendeeStatusFromJSONTyped(json, false);
}

export function AttendeeStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): AttendeeStatus {
    return json as AttendeeStatus;
}

export function AttendeeStatusToJSON(value?: AttendeeStatus | null): any {
    return value as any;
}

export function AttendeeStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): AttendeeStatus {
    return value as AttendeeStatus;
}

