/* tslint:disable */
/* eslint-disable */
/**
 * Omnidapter Server
 * Self-hosted REST API wrapping the Omnidapter calendar integration library
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConferenceEntryPoint } from './ConferenceEntryPoint';
import {
    ConferenceEntryPointFromJSON,
    ConferenceEntryPointFromJSONTyped,
    ConferenceEntryPointToJSON,
    ConferenceEntryPointToJSONTyped,
} from './ConferenceEntryPoint';

/**
 * Conference/video call information attached to an event.
 * @export
 * @interface ConferenceData
 */
export interface ConferenceData {
    /**
     * 
     * @type {string}
     * @memberof ConferenceData
     */
    conferenceId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ConferenceData
     */
    conferenceSolutionName?: string | null;
    /**
     * 
     * @type {Array<ConferenceEntryPoint>}
     * @memberof ConferenceData
     */
    entryPoints?: Array<ConferenceEntryPoint>;
    /**
     * 
     * @type {string}
     * @memberof ConferenceData
     */
    joinUrl?: string | null;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof ConferenceData
     */
    providerData?: { [key: string]: any; } | null;
}

/**
 * Check if a given object implements the ConferenceData interface.
 */
export function instanceOfConferenceData(value: object): value is ConferenceData {
    return true;
}

export function ConferenceDataFromJSON(json: any): ConferenceData {
    return ConferenceDataFromJSONTyped(json, false);
}

export function ConferenceDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConferenceData {
    if (json == null) {
        return json;
    }
    return {
        
        'conferenceId': json['conference_id'] == null ? undefined : json['conference_id'],
        'conferenceSolutionName': json['conference_solution_name'] == null ? undefined : json['conference_solution_name'],
        'entryPoints': json['entry_points'] == null ? undefined : ((json['entry_points'] as Array<any>).map(ConferenceEntryPointFromJSON)),
        'joinUrl': json['join_url'] == null ? undefined : json['join_url'],
        'providerData': json['provider_data'] == null ? undefined : json['provider_data'],
    };
}

export function ConferenceDataToJSON(json: any): ConferenceData {
    return ConferenceDataToJSONTyped(json, false);
}

export function ConferenceDataToJSONTyped(value?: ConferenceData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'conference_id': value['conferenceId'],
        'conference_solution_name': value['conferenceSolutionName'],
        'entry_points': value['entryPoints'] == null ? undefined : ((value['entryPoints'] as Array<any>).map(ConferenceEntryPointToJSON)),
        'join_url': value['joinUrl'],
        'provider_data': value['providerData'],
    };
}

