/* tslint:disable */
/* eslint-disable */
/**
 * Omnidapter Server
 * Self-hosted REST API wrapping the Omnidapter calendar integration library
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A single entry point for a conference (e.g., video URL, phone dial-in).
 * @export
 * @interface ConferenceEntryPoint
 */
export interface ConferenceEntryPoint {
    /**
     * 
     * @type {string}
     * @memberof ConferenceEntryPoint
     */
    entryPointType: string;
    /**
     * 
     * @type {string}
     * @memberof ConferenceEntryPoint
     */
    uri: string;
    /**
     * 
     * @type {string}
     * @memberof ConferenceEntryPoint
     */
    label?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ConferenceEntryPoint
     */
    pin?: string | null;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof ConferenceEntryPoint
     */
    providerData?: { [key: string]: any; } | null;
}

/**
 * Check if a given object implements the ConferenceEntryPoint interface.
 */
export function instanceOfConferenceEntryPoint(value: object): value is ConferenceEntryPoint {
    if (!('entryPointType' in value) || value['entryPointType'] === undefined) return false;
    if (!('uri' in value) || value['uri'] === undefined) return false;
    return true;
}

export function ConferenceEntryPointFromJSON(json: any): ConferenceEntryPoint {
    return ConferenceEntryPointFromJSONTyped(json, false);
}

export function ConferenceEntryPointFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConferenceEntryPoint {
    if (json == null) {
        return json;
    }
    return {
        
        'entryPointType': json['entry_point_type'],
        'uri': json['uri'],
        'label': json['label'] == null ? undefined : json['label'],
        'pin': json['pin'] == null ? undefined : json['pin'],
        'providerData': json['provider_data'] == null ? undefined : json['provider_data'],
    };
}

export function ConferenceEntryPointToJSON(json: any): ConferenceEntryPoint {
    return ConferenceEntryPointToJSONTyped(json, false);
}

export function ConferenceEntryPointToJSONTyped(value?: ConferenceEntryPoint | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'entry_point_type': value['entryPointType'],
        'uri': value['uri'],
        'label': value['label'],
        'pin': value['pin'],
        'provider_data': value['providerData'],
    };
}

