/* tslint:disable */
/* eslint-disable */
/**
 * Omnidapter Server
 * Self-hosted REST API wrapping the Omnidapter calendar integration library
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request body for POST /connect/connections.
 * @export
 * @interface ConnectCreateConnectionRequest
 */
export interface ConnectCreateConnectionRequest {
    /**
     * 
     * @type {string}
     * @memberof ConnectCreateConnectionRequest
     */
    providerKey: string;
    /**
     * 
     * @type {string}
     * @memberof ConnectCreateConnectionRequest
     */
    externalId?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof ConnectCreateConnectionRequest
     */
    scopes?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof ConnectCreateConnectionRequest
     */
    redirectUri?: string | null;
    /**
     * 
     * @type {{ [key: string]: string | null; }}
     * @memberof ConnectCreateConnectionRequest
     */
    credentials?: { [key: string]: string | null; } | null;
}

/**
 * Check if a given object implements the ConnectCreateConnectionRequest interface.
 */
export function instanceOfConnectCreateConnectionRequest(value: object): value is ConnectCreateConnectionRequest {
    if (!('providerKey' in value) || value['providerKey'] === undefined) return false;
    return true;
}

export function ConnectCreateConnectionRequestFromJSON(json: any): ConnectCreateConnectionRequest {
    return ConnectCreateConnectionRequestFromJSONTyped(json, false);
}

export function ConnectCreateConnectionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConnectCreateConnectionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'providerKey': json['provider_key'],
        'externalId': json['external_id'] == null ? undefined : json['external_id'],
        'scopes': json['scopes'] == null ? undefined : json['scopes'],
        'redirectUri': json['redirect_uri'] == null ? undefined : json['redirect_uri'],
        'credentials': json['credentials'] == null ? undefined : json['credentials'],
    };
}

export function ConnectCreateConnectionRequestToJSON(json: any): ConnectCreateConnectionRequest {
    return ConnectCreateConnectionRequestToJSONTyped(json, false);
}

export function ConnectCreateConnectionRequestToJSONTyped(value?: ConnectCreateConnectionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'provider_key': value['providerKey'],
        'external_id': value['externalId'],
        'scopes': value['scopes'],
        'redirect_uri': value['redirectUri'],
        'credentials': value['credentials'],
    };
}

