/* tslint:disable */
/* eslint-disable */
/**
 * Omnidapter Server
 * Self-hosted REST API wrapping the Omnidapter calendar integration library
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConferenceData } from './ConferenceData';
import {
    ConferenceDataFromJSON,
    ConferenceDataFromJSONTyped,
    ConferenceDataToJSON,
    ConferenceDataToJSONTyped,
} from './ConferenceData';
import type { Recurrence } from './Recurrence';
import {
    RecurrenceFromJSON,
    RecurrenceFromJSONTyped,
    RecurrenceToJSON,
    RecurrenceToJSONTyped,
} from './Recurrence';
import type { Reminder } from './Reminder';
import {
    ReminderFromJSON,
    ReminderFromJSONTyped,
    ReminderToJSON,
    ReminderToJSONTyped,
} from './Reminder';
import type { Start } from './Start';
import {
    StartFromJSON,
    StartFromJSONTyped,
    StartToJSON,
    StartToJSONTyped,
} from './Start';
import type { EventStatus } from './EventStatus';
import {
    EventStatusFromJSON,
    EventStatusFromJSONTyped,
    EventStatusToJSON,
    EventStatusToJSONTyped,
} from './EventStatus';
import type { End } from './End';
import {
    EndFromJSON,
    EndFromJSONTyped,
    EndToJSON,
    EndToJSONTyped,
} from './End';
import type { Attendee } from './Attendee';
import {
    AttendeeFromJSON,
    AttendeeFromJSONTyped,
    AttendeeToJSON,
    AttendeeToJSONTyped,
} from './Attendee';

/**
 * Request model for creating a calendar event.
 * 
 * When used via the REST API, ``calendar_id`` is injected from the URL path
 * parameter and must not be set in the request body.  When using the Python
 * library directly, callers must supply a non-empty ``calendar_id``.
 * @export
 * @interface CreateEventRequest
 */
export interface CreateEventRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateEventRequest
     */
    calendarId?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateEventRequest
     */
    summary: string;
    /**
     * 
     * @type {Start}
     * @memberof CreateEventRequest
     */
    start: Start;
    /**
     * 
     * @type {End}
     * @memberof CreateEventRequest
     */
    end: End;
    /**
     * 
     * @type {boolean}
     * @memberof CreateEventRequest
     */
    allDay?: boolean;
    /**
     * 
     * @type {string}
     * @memberof CreateEventRequest
     */
    timezone?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateEventRequest
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateEventRequest
     */
    location?: string | null;
    /**
     * 
     * @type {Array<Attendee>}
     * @memberof CreateEventRequest
     */
    attendees?: Array<Attendee>;
    /**
     * 
     * @type {Recurrence}
     * @memberof CreateEventRequest
     */
    recurrence?: Recurrence | null;
    /**
     * 
     * @type {ConferenceData}
     * @memberof CreateEventRequest
     */
    conferenceData?: ConferenceData | null;
    /**
     * 
     * @type {Reminder}
     * @memberof CreateEventRequest
     */
    reminders?: Reminder | null;
    /**
     * 
     * @type {string}
     * @memberof CreateEventRequest
     */
    visibility?: string | null;
    /**
     * 
     * @type {EventStatus}
     * @memberof CreateEventRequest
     */
    status?: EventStatus | null;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof CreateEventRequest
     */
    extra?: { [key: string]: any; };
}



/**
 * Check if a given object implements the CreateEventRequest interface.
 */
export function instanceOfCreateEventRequest(value: object): value is CreateEventRequest {
    if (!('summary' in value) || value['summary'] === undefined) return false;
    if (!('start' in value) || value['start'] === undefined) return false;
    if (!('end' in value) || value['end'] === undefined) return false;
    return true;
}

export function CreateEventRequestFromJSON(json: any): CreateEventRequest {
    return CreateEventRequestFromJSONTyped(json, false);
}

export function CreateEventRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateEventRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'calendarId': json['calendar_id'] == null ? undefined : json['calendar_id'],
        'summary': json['summary'],
        'start': StartFromJSON(json['start']),
        'end': EndFromJSON(json['end']),
        'allDay': json['all_day'] == null ? undefined : json['all_day'],
        'timezone': json['timezone'] == null ? undefined : json['timezone'],
        'description': json['description'] == null ? undefined : json['description'],
        'location': json['location'] == null ? undefined : json['location'],
        'attendees': json['attendees'] == null ? undefined : ((json['attendees'] as Array<any>).map(AttendeeFromJSON)),
        'recurrence': json['recurrence'] == null ? undefined : RecurrenceFromJSON(json['recurrence']),
        'conferenceData': json['conference_data'] == null ? undefined : ConferenceDataFromJSON(json['conference_data']),
        'reminders': json['reminders'] == null ? undefined : ReminderFromJSON(json['reminders']),
        'visibility': json['visibility'] == null ? undefined : json['visibility'],
        'status': json['status'] == null ? undefined : EventStatusFromJSON(json['status']),
        'extra': json['extra'] == null ? undefined : json['extra'],
    };
}

export function CreateEventRequestToJSON(json: any): CreateEventRequest {
    return CreateEventRequestToJSONTyped(json, false);
}

export function CreateEventRequestToJSONTyped(value?: CreateEventRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'calendar_id': value['calendarId'],
        'summary': value['summary'],
        'start': StartToJSON(value['start']),
        'end': EndToJSON(value['end']),
        'all_day': value['allDay'],
        'timezone': value['timezone'],
        'description': value['description'],
        'location': value['location'],
        'attendees': value['attendees'] == null ? undefined : ((value['attendees'] as Array<any>).map(AttendeeToJSON)),
        'recurrence': RecurrenceToJSON(value['recurrence']),
        'conference_data': ConferenceDataToJSON(value['conferenceData']),
        'reminders': ReminderToJSON(value['reminders']),
        'visibility': value['visibility'],
        'status': EventStatusToJSON(value['status']),
        'extra': value['extra'],
    };
}

