/* tslint:disable */
/* eslint-disable */
/**
 * Omnidapter Server
 * Self-hosted REST API wrapping the Omnidapter calendar integration library
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateLinkTokenRequest
 */
export interface CreateLinkTokenRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateLinkTokenRequest
     */
    endUserId?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateLinkTokenRequest
     */
    allowedProviders?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof CreateLinkTokenRequest
     */
    redirectUri?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CreateLinkTokenRequest
     */
    ttlSeconds?: number | null;
    /**
     * 
     * @type {string}
     * @memberof CreateLinkTokenRequest
     */
    connectionId?: string | null;
}

/**
 * Check if a given object implements the CreateLinkTokenRequest interface.
 */
export function instanceOfCreateLinkTokenRequest(value: object): value is CreateLinkTokenRequest {
    return true;
}

export function CreateLinkTokenRequestFromJSON(json: any): CreateLinkTokenRequest {
    return CreateLinkTokenRequestFromJSONTyped(json, false);
}

export function CreateLinkTokenRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateLinkTokenRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'endUserId': json['end_user_id'] == null ? undefined : json['end_user_id'],
        'allowedProviders': json['allowed_providers'] == null ? undefined : json['allowed_providers'],
        'redirectUri': json['redirect_uri'] == null ? undefined : json['redirect_uri'],
        'ttlSeconds': json['ttl_seconds'] == null ? undefined : json['ttl_seconds'],
        'connectionId': json['connection_id'] == null ? undefined : json['connection_id'],
    };
}

export function CreateLinkTokenRequestToJSON(json: any): CreateLinkTokenRequest {
    return CreateLinkTokenRequestToJSONTyped(json, false);
}

export function CreateLinkTokenRequestToJSONTyped(value?: CreateLinkTokenRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'end_user_id': value['endUserId'],
        'allowed_providers': value['allowedProviders'],
        'redirect_uri': value['redirectUri'],
        'ttl_seconds': value['ttlSeconds'],
        'connection_id': value['connectionId'],
    };
}

