/* tslint:disable */
/* eslint-disable */
/**
 * Omnidapter Server
 * Self-hosted REST API wrapping the Omnidapter calendar integration library
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request model for creating a calendar.
 * @export
 * @interface CreateCalendarRequest
 */
export interface CreateCalendarRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateCalendarRequest
     */
    summary: string;
    /**
     * 
     * @type {string}
     * @memberof CreateCalendarRequest
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateCalendarRequest
     */
    timezone?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateCalendarRequest
     */
    backgroundColor?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateCalendarRequest
     */
    foregroundColor?: string | null;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof CreateCalendarRequest
     */
    extra?: { [key: string]: any; };
}

/**
 * Check if a given object implements the CreateCalendarRequest interface.
 */
export function instanceOfCreateCalendarRequest(value: object): value is CreateCalendarRequest {
    if (!('summary' in value) || value['summary'] === undefined) return false;
    return true;
}

export function CreateCalendarRequestFromJSON(json: any): CreateCalendarRequest {
    return CreateCalendarRequestFromJSONTyped(json, false);
}

export function CreateCalendarRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCalendarRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'summary': json['summary'],
        'description': json['description'] == null ? undefined : json['description'],
        'timezone': json['timezone'] == null ? undefined : json['timezone'],
        'backgroundColor': json['background_color'] == null ? undefined : json['background_color'],
        'foregroundColor': json['foreground_color'] == null ? undefined : json['foreground_color'],
        'extra': json['extra'] == null ? undefined : json['extra'],
    };
}

export function CreateCalendarRequestToJSON(json: any): CreateCalendarRequest {
    return CreateCalendarRequestToJSONTyped(json, false);
}

export function CreateCalendarRequestToJSONTyped(value?: CreateCalendarRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'summary': value['summary'],
        'description': value['description'],
        'timezone': value['timezone'],
        'background_color': value['backgroundColor'],
        'foreground_color': value['foregroundColor'],
        'extra': value['extra'],
    };
}

