/* tslint:disable */
/* eslint-disable */
/**
 * Omnidapter Server
 * Self-hosted REST API wrapping the Omnidapter calendar integration library
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OriginalStartTime
 */
export interface OriginalStartTime {
}

/**
 * Check if a given object implements the OriginalStartTime interface.
 */
export function instanceOfOriginalStartTime(value: object): value is OriginalStartTime {
    return true;
}

export function OriginalStartTimeFromJSON(json: any): OriginalStartTime {
    return OriginalStartTimeFromJSONTyped(json, false);
}

export function OriginalStartTimeFromJSONTyped(json: any, ignoreDiscriminator: boolean): OriginalStartTime {
    return json;
}

export function OriginalStartTimeToJSON(json: any): OriginalStartTime {
    return OriginalStartTimeToJSONTyped(json, false);
}

export function OriginalStartTimeToJSONTyped(value?: OriginalStartTime | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

