/* tslint:disable */
/* eslint-disable */
/**
 * Omnidapter Server
 * Self-hosted REST API wrapping the Omnidapter calendar integration library
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReauthorizeConnectionRequest
 */
export interface ReauthorizeConnectionRequest {
    /**
     * 
     * @type {string}
     * @memberof ReauthorizeConnectionRequest
     */
    redirectUrl: string;
}

/**
 * Check if a given object implements the ReauthorizeConnectionRequest interface.
 */
export function instanceOfReauthorizeConnectionRequest(value: object): value is ReauthorizeConnectionRequest {
    if (!('redirectUrl' in value) || value['redirectUrl'] === undefined) return false;
    return true;
}

export function ReauthorizeConnectionRequestFromJSON(json: any): ReauthorizeConnectionRequest {
    return ReauthorizeConnectionRequestFromJSONTyped(json, false);
}

export function ReauthorizeConnectionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReauthorizeConnectionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'redirectUrl': json['redirect_url'],
    };
}

export function ReauthorizeConnectionRequestToJSON(json: any): ReauthorizeConnectionRequest {
    return ReauthorizeConnectionRequestToJSONTyped(json, false);
}

export function ReauthorizeConnectionRequestToJSONTyped(value?: ReauthorizeConnectionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'redirect_url': value['redirectUrl'],
    };
}

