/* tslint:disable */
/* eslint-disable */
/**
 * Omnidapter Server
 * Self-hosted REST API wrapping the Omnidapter calendar integration library
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OriginalStartTime } from './OriginalStartTime';
import {
    OriginalStartTimeFromJSON,
    OriginalStartTimeFromJSONTyped,
    OriginalStartTimeToJSON,
    OriginalStartTimeToJSONTyped,
} from './OriginalStartTime';

/**
 * Recurrence information for recurring events.
 * 
 * `rules` contains RRULE/EXRULE/RDATE/EXDATE strings (RFC 5545 format).
 * @export
 * @interface Recurrence
 */
export interface Recurrence {
    /**
     * 
     * @type {Array<string>}
     * @memberof Recurrence
     */
    rules?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof Recurrence
     */
    recurringEventId?: string | null;
    /**
     * 
     * @type {OriginalStartTime}
     * @memberof Recurrence
     */
    originalStartTime?: OriginalStartTime | null;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof Recurrence
     */
    providerData?: { [key: string]: any; } | null;
}

/**
 * Check if a given object implements the Recurrence interface.
 */
export function instanceOfRecurrence(value: object): value is Recurrence {
    return true;
}

export function RecurrenceFromJSON(json: any): Recurrence {
    return RecurrenceFromJSONTyped(json, false);
}

export function RecurrenceFromJSONTyped(json: any, ignoreDiscriminator: boolean): Recurrence {
    if (json == null) {
        return json;
    }
    return {
        
        'rules': json['rules'] == null ? undefined : json['rules'],
        'recurringEventId': json['recurring_event_id'] == null ? undefined : json['recurring_event_id'],
        'originalStartTime': json['original_start_time'] == null ? undefined : OriginalStartTimeFromJSON(json['original_start_time']),
        'providerData': json['provider_data'] == null ? undefined : json['provider_data'],
    };
}

export function RecurrenceToJSON(json: any): Recurrence {
    return RecurrenceToJSONTyped(json, false);
}

export function RecurrenceToJSONTyped(value?: Recurrence | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'rules': value['rules'],
        'recurring_event_id': value['recurringEventId'],
        'original_start_time': OriginalStartTimeToJSON(value['originalStartTime']),
        'provider_data': value['providerData'],
    };
}

