/* tslint:disable */
/* eslint-disable */
/**
 * Omnidapter Server
 * Self-hosted REST API wrapping the Omnidapter calendar integration library
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ReminderOverride } from './ReminderOverride';
import {
    ReminderOverrideFromJSON,
    ReminderOverrideFromJSONTyped,
    ReminderOverrideToJSON,
    ReminderOverrideToJSONTyped,
} from './ReminderOverride';

/**
 * Reminder configuration for an event.
 * @export
 * @interface Reminder
 */
export interface Reminder {
    /**
     * 
     * @type {boolean}
     * @memberof Reminder
     */
    useDefault?: boolean;
    /**
     * 
     * @type {Array<ReminderOverride>}
     * @memberof Reminder
     */
    overrides?: Array<ReminderOverride>;
}

/**
 * Check if a given object implements the Reminder interface.
 */
export function instanceOfReminder(value: object): value is Reminder {
    return true;
}

export function ReminderFromJSON(json: any): Reminder {
    return ReminderFromJSONTyped(json, false);
}

export function ReminderFromJSONTyped(json: any, ignoreDiscriminator: boolean): Reminder {
    if (json == null) {
        return json;
    }
    return {
        
        'useDefault': json['use_default'] == null ? undefined : json['use_default'],
        'overrides': json['overrides'] == null ? undefined : ((json['overrides'] as Array<any>).map(ReminderOverrideFromJSON)),
    };
}

export function ReminderToJSON(json: any): Reminder {
    return ReminderToJSONTyped(json, false);
}

export function ReminderToJSONTyped(value?: Reminder | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'use_default': value['useDefault'],
        'overrides': value['overrides'] == null ? undefined : ((value['overrides'] as Array<any>).map(ReminderOverrideToJSON)),
    };
}

