/* tslint:disable */
/* eslint-disable */
/**
 * Omnidapter Server
 * Self-hosted REST API wrapping the Omnidapter calendar integration library
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A single reminder override for an event.
 * @export
 * @interface ReminderOverride
 */
export interface ReminderOverride {
    /**
     * 
     * @type {string}
     * @memberof ReminderOverride
     */
    method: string;
    /**
     * 
     * @type {number}
     * @memberof ReminderOverride
     */
    minutesBefore: number;
}

/**
 * Check if a given object implements the ReminderOverride interface.
 */
export function instanceOfReminderOverride(value: object): value is ReminderOverride {
    if (!('method' in value) || value['method'] === undefined) return false;
    if (!('minutesBefore' in value) || value['minutesBefore'] === undefined) return false;
    return true;
}

export function ReminderOverrideFromJSON(json: any): ReminderOverride {
    return ReminderOverrideFromJSONTyped(json, false);
}

export function ReminderOverrideFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReminderOverride {
    if (json == null) {
        return json;
    }
    return {
        
        'method': json['method'],
        'minutesBefore': json['minutes_before'],
    };
}

export function ReminderOverrideToJSON(json: any): ReminderOverride {
    return ReminderOverrideToJSONTyped(json, false);
}

export function ReminderOverrideToJSONTyped(value?: ReminderOverride | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'method': value['method'],
        'minutes_before': value['minutesBefore'],
    };
}

