/* tslint:disable */
/* eslint-disable */
/**
 * Omnidapter Server
 * Self-hosted REST API wrapping the Omnidapter calendar integration library
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConferenceData } from './ConferenceData';
import {
    ConferenceDataFromJSON,
    ConferenceDataFromJSONTyped,
    ConferenceDataToJSON,
    ConferenceDataToJSONTyped,
} from './ConferenceData';
import type { Recurrence } from './Recurrence';
import {
    RecurrenceFromJSON,
    RecurrenceFromJSONTyped,
    RecurrenceToJSON,
    RecurrenceToJSONTyped,
} from './Recurrence';
import type { Reminder } from './Reminder';
import {
    ReminderFromJSON,
    ReminderFromJSONTyped,
    ReminderToJSON,
    ReminderToJSONTyped,
} from './Reminder';
import type { End1 } from './End1';
import {
    End1FromJSON,
    End1FromJSONTyped,
    End1ToJSON,
    End1ToJSONTyped,
} from './End1';
import type { EventStatus } from './EventStatus';
import {
    EventStatusFromJSON,
    EventStatusFromJSONTyped,
    EventStatusToJSON,
    EventStatusToJSONTyped,
} from './EventStatus';
import type { Start1 } from './Start1';
import {
    Start1FromJSON,
    Start1FromJSONTyped,
    Start1ToJSON,
    Start1ToJSONTyped,
} from './Start1';
import type { Attendee } from './Attendee';
import {
    AttendeeFromJSON,
    AttendeeFromJSONTyped,
    AttendeeToJSON,
    AttendeeToJSONTyped,
} from './Attendee';

/**
 * Request model for updating a calendar event.
 * 
 * When used via the REST API, ``calendar_id`` and ``event_id`` are injected
 * from URL path parameters.  When using the Python library directly, callers
 * must supply non-empty values for both fields.
 * @export
 * @interface UpdateEventRequest
 */
export interface UpdateEventRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateEventRequest
     */
    calendarId?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateEventRequest
     */
    eventId?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateEventRequest
     */
    summary?: string | null;
    /**
     * 
     * @type {Start1}
     * @memberof UpdateEventRequest
     */
    start?: Start1 | null;
    /**
     * 
     * @type {End1}
     * @memberof UpdateEventRequest
     */
    end?: End1 | null;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateEventRequest
     */
    allDay?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateEventRequest
     */
    timezone?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateEventRequest
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateEventRequest
     */
    location?: string | null;
    /**
     * 
     * @type {Array<Attendee>}
     * @memberof UpdateEventRequest
     */
    attendees?: Array<Attendee> | null;
    /**
     * 
     * @type {Recurrence}
     * @memberof UpdateEventRequest
     */
    recurrence?: Recurrence | null;
    /**
     * 
     * @type {ConferenceData}
     * @memberof UpdateEventRequest
     */
    conferenceData?: ConferenceData | null;
    /**
     * 
     * @type {Reminder}
     * @memberof UpdateEventRequest
     */
    reminders?: Reminder | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateEventRequest
     */
    visibility?: string | null;
    /**
     * 
     * @type {EventStatus}
     * @memberof UpdateEventRequest
     */
    status?: EventStatus | null;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof UpdateEventRequest
     */
    extra?: { [key: string]: any; };
}



/**
 * Check if a given object implements the UpdateEventRequest interface.
 */
export function instanceOfUpdateEventRequest(value: object): value is UpdateEventRequest {
    return true;
}

export function UpdateEventRequestFromJSON(json: any): UpdateEventRequest {
    return UpdateEventRequestFromJSONTyped(json, false);
}

export function UpdateEventRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateEventRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'calendarId': json['calendar_id'] == null ? undefined : json['calendar_id'],
        'eventId': json['event_id'] == null ? undefined : json['event_id'],
        'summary': json['summary'] == null ? undefined : json['summary'],
        'start': json['start'] == null ? undefined : Start1FromJSON(json['start']),
        'end': json['end'] == null ? undefined : End1FromJSON(json['end']),
        'allDay': json['all_day'] == null ? undefined : json['all_day'],
        'timezone': json['timezone'] == null ? undefined : json['timezone'],
        'description': json['description'] == null ? undefined : json['description'],
        'location': json['location'] == null ? undefined : json['location'],
        'attendees': json['attendees'] == null ? undefined : ((json['attendees'] as Array<any>).map(AttendeeFromJSON)),
        'recurrence': json['recurrence'] == null ? undefined : RecurrenceFromJSON(json['recurrence']),
        'conferenceData': json['conference_data'] == null ? undefined : ConferenceDataFromJSON(json['conference_data']),
        'reminders': json['reminders'] == null ? undefined : ReminderFromJSON(json['reminders']),
        'visibility': json['visibility'] == null ? undefined : json['visibility'],
        'status': json['status'] == null ? undefined : EventStatusFromJSON(json['status']),
        'extra': json['extra'] == null ? undefined : json['extra'],
    };
}

export function UpdateEventRequestToJSON(json: any): UpdateEventRequest {
    return UpdateEventRequestToJSONTyped(json, false);
}

export function UpdateEventRequestToJSONTyped(value?: UpdateEventRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'calendar_id': value['calendarId'],
        'event_id': value['eventId'],
        'summary': value['summary'],
        'start': Start1ToJSON(value['start']),
        'end': End1ToJSON(value['end']),
        'all_day': value['allDay'],
        'timezone': value['timezone'],
        'description': value['description'],
        'location': value['location'],
        'attendees': value['attendees'] == null ? undefined : ((value['attendees'] as Array<any>).map(AttendeeToJSON)),
        'recurrence': RecurrenceToJSON(value['recurrence']),
        'conference_data': ConferenceDataToJSON(value['conferenceData']),
        'reminders': ReminderToJSON(value['reminders']),
        'visibility': value['visibility'],
        'status': EventStatusToJSON(value['status']),
        'extra': value['extra'],
    };
}

