/* tslint:disable */
/* eslint-disable */
/**
 * Omnidapter Server
 * Self-hosted REST API wrapping the Omnidapter calendar integration library
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request model for updating a calendar.
 * 
 * When used via the REST API, ``calendar_id`` is injected from the URL path
 * parameter.  When using the Python library directly, callers must supply a
 * non-empty ``calendar_id``.
 * @export
 * @interface UpdateCalendarRequest
 */
export interface UpdateCalendarRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateCalendarRequest
     */
    calendarId?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateCalendarRequest
     */
    summary?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateCalendarRequest
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateCalendarRequest
     */
    timezone?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateCalendarRequest
     */
    backgroundColor?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateCalendarRequest
     */
    foregroundColor?: string | null;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof UpdateCalendarRequest
     */
    extra?: { [key: string]: any; };
}

/**
 * Check if a given object implements the UpdateCalendarRequest interface.
 */
export function instanceOfUpdateCalendarRequest(value: object): value is UpdateCalendarRequest {
    return true;
}

export function UpdateCalendarRequestFromJSON(json: any): UpdateCalendarRequest {
    return UpdateCalendarRequestFromJSONTyped(json, false);
}

export function UpdateCalendarRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateCalendarRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'calendarId': json['calendar_id'] == null ? undefined : json['calendar_id'],
        'summary': json['summary'] == null ? undefined : json['summary'],
        'description': json['description'] == null ? undefined : json['description'],
        'timezone': json['timezone'] == null ? undefined : json['timezone'],
        'backgroundColor': json['background_color'] == null ? undefined : json['background_color'],
        'foregroundColor': json['foreground_color'] == null ? undefined : json['foreground_color'],
        'extra': json['extra'] == null ? undefined : json['extra'],
    };
}

export function UpdateCalendarRequestToJSON(json: any): UpdateCalendarRequest {
    return UpdateCalendarRequestToJSONTyped(json, false);
}

export function UpdateCalendarRequestToJSONTyped(value?: UpdateCalendarRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'calendar_id': value['calendarId'],
        'summary': value['summary'],
        'description': value['description'],
        'timezone': value['timezone'],
        'background_color': value['backgroundColor'],
        'foreground_color': value['foregroundColor'],
        'extra': value['extra'],
    };
}

