# This file was auto-generated by Fern from our API Definition.

import typing
from ..core.client_wrapper import SyncClientWrapper
from ..core.request_options import RequestOptions
from ..core.pydantic_utilities import parse_obj_as
from ..errors.unprocessable_entity_error import UnprocessableEntityError
from ..types.http_validation_error import HttpValidationError
from json.decoder import JSONDecodeError
from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class LinkTokensClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def create_link_token_endpoint(
        self,
        *,
        end_user_id: typing.Optional[str] = OMIT,
        allowed_providers: typing.Optional[typing.Sequence[str]] = OMIT,
        redirect_uri: typing.Optional[str] = OMIT,
        ttl_seconds: typing.Optional[int] = OMIT,
        connection_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Optional[typing.Any]:
        """
        Create a short-lived link token for the Connect UI.

        Pass the returned token to the embedded or redirect Connect UI as a
        Bearer token. The token grants permission to list providers and initiate
        a connection on behalf of the tenant, scoped to ``end_user_id`` if provided.

        Set ``connection_id`` to create a *reconnect* token — the connect UI will
        skip provider selection and go directly to the authorization flow for the
        existing connection.

        Parameters
        ----------
        end_user_id : typing.Optional[str]

        allowed_providers : typing.Optional[typing.Sequence[str]]

        redirect_uri : typing.Optional[str]

        ttl_seconds : typing.Optional[int]

        connection_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Optional[typing.Any]
            Successful Response

        Examples
        --------
        from omnidapter_sdk import OmnidapterApi

        client = OmnidapterApi(
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )
        client.link_tokens.create_link_token_endpoint()
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/link-tokens",
            method="POST",
            json={
                "end_user_id": end_user_id,
                "allowed_providers": allowed_providers,
                "redirect_uri": redirect_uri,
                "ttl_seconds": ttl_seconds,
                "connection_id": connection_id,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    typing.Optional[typing.Any],
                    parse_obj_as(
                        type_=typing.Optional[typing.Any],  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)


class AsyncLinkTokensClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def create_link_token_endpoint(
        self,
        *,
        end_user_id: typing.Optional[str] = OMIT,
        allowed_providers: typing.Optional[typing.Sequence[str]] = OMIT,
        redirect_uri: typing.Optional[str] = OMIT,
        ttl_seconds: typing.Optional[int] = OMIT,
        connection_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Optional[typing.Any]:
        """
        Create a short-lived link token for the Connect UI.

        Pass the returned token to the embedded or redirect Connect UI as a
        Bearer token. The token grants permission to list providers and initiate
        a connection on behalf of the tenant, scoped to ``end_user_id`` if provided.

        Set ``connection_id`` to create a *reconnect* token — the connect UI will
        skip provider selection and go directly to the authorization flow for the
        existing connection.

        Parameters
        ----------
        end_user_id : typing.Optional[str]

        allowed_providers : typing.Optional[typing.Sequence[str]]

        redirect_uri : typing.Optional[str]

        ttl_seconds : typing.Optional[int]

        connection_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Optional[typing.Any]
            Successful Response

        Examples
        --------
        import asyncio

        from omnidapter_sdk import AsyncOmnidapterApi

        client = AsyncOmnidapterApi(
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.link_tokens.create_link_token_endpoint()


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/link-tokens",
            method="POST",
            json={
                "end_user_id": end_user_id,
                "allowed_providers": allowed_providers,
                "redirect_uri": redirect_uri,
                "ttl_seconds": ttl_seconds,
                "connection_id": connection_id,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    typing.Optional[typing.Any],
                    parse_obj_as(
                        type_=typing.Optional[typing.Any],  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)
