// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as OmnidapterApi from "../../../index.js";

export declare namespace DashboardClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class DashboardClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<DashboardClient.Options>;

    constructor(options: DashboardClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * @param {DashboardClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.dashboard.getProfile()
     */
    public getProfile(requestOptions?: DashboardClient.RequestOptions): core.HttpResponsePromise<unknown> {
        return core.HttpResponsePromise.fromPromise(this.__getProfile(requestOptions));
    }

    private async __getProfile(
        requestOptions?: DashboardClient.RequestOptions,
    ): Promise<core.WithRawResponse<unknown>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "v1/dashboard/profile",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.OmnidapterApiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/v1/dashboard/profile");
    }

    /**
     * @param {OmnidapterApi.UpdateProfileRequest} request
     * @param {DashboardClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link OmnidapterApi.UnprocessableEntityError}
     *
     * @example
     *     await client.dashboard.updateProfile({
     *         name: "name"
     *     })
     */
    public updateProfile(
        request: OmnidapterApi.UpdateProfileRequest,
        requestOptions?: DashboardClient.RequestOptions,
    ): core.HttpResponsePromise<unknown> {
        return core.HttpResponsePromise.fromPromise(this.__updateProfile(request, requestOptions));
    }

    private async __updateProfile(
        request: OmnidapterApi.UpdateProfileRequest,
        requestOptions?: DashboardClient.RequestOptions,
    ): Promise<core.WithRawResponse<unknown>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "v1/dashboard/profile",
            ),
            method: "PATCH",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new OmnidapterApi.UnprocessableEntityError(
                        _response.error.body as OmnidapterApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.OmnidapterApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "PATCH", "/v1/dashboard/profile");
    }

    /**
     * @param {DashboardClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.dashboard.getTenant()
     */
    public getTenant(requestOptions?: DashboardClient.RequestOptions): core.HttpResponsePromise<unknown> {
        return core.HttpResponsePromise.fromPromise(this.__getTenant(requestOptions));
    }

    private async __getTenant(requestOptions?: DashboardClient.RequestOptions): Promise<core.WithRawResponse<unknown>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "v1/dashboard/tenant",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.OmnidapterApiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/v1/dashboard/tenant");
    }

    /**
     * @param {OmnidapterApi.UpdateTenantRequest} request
     * @param {DashboardClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link OmnidapterApi.UnprocessableEntityError}
     *
     * @example
     *     await client.dashboard.patchTenant({
     *         name: "name"
     *     })
     */
    public patchTenant(
        request: OmnidapterApi.UpdateTenantRequest,
        requestOptions?: DashboardClient.RequestOptions,
    ): core.HttpResponsePromise<unknown> {
        return core.HttpResponsePromise.fromPromise(this.__patchTenant(request, requestOptions));
    }

    private async __patchTenant(
        request: OmnidapterApi.UpdateTenantRequest,
        requestOptions?: DashboardClient.RequestOptions,
    ): Promise<core.WithRawResponse<unknown>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "v1/dashboard/tenant",
            ),
            method: "PATCH",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new OmnidapterApi.UnprocessableEntityError(
                        _response.error.body as OmnidapterApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.OmnidapterApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "PATCH", "/v1/dashboard/tenant");
    }

    /**
     * @param {DashboardClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.dashboard.getMembers()
     */
    public getMembers(requestOptions?: DashboardClient.RequestOptions): core.HttpResponsePromise<unknown> {
        return core.HttpResponsePromise.fromPromise(this.__getMembers(requestOptions));
    }

    private async __getMembers(
        requestOptions?: DashboardClient.RequestOptions,
    ): Promise<core.WithRawResponse<unknown>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "v1/dashboard/members",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.OmnidapterApiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/v1/dashboard/members");
    }

    /**
     * @param {OmnidapterApi.DeleteMemberV1DashboardMembersUserIdDeleteRequest} request
     * @param {DashboardClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link OmnidapterApi.UnprocessableEntityError}
     *
     * @example
     *     await client.dashboard.deleteMember({
     *         user_id: "user_id"
     *     })
     */
    public deleteMember(
        request: OmnidapterApi.DeleteMemberV1DashboardMembersUserIdDeleteRequest,
        requestOptions?: DashboardClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__deleteMember(request, requestOptions));
    }

    private async __deleteMember(
        request: OmnidapterApi.DeleteMemberV1DashboardMembersUserIdDeleteRequest,
        requestOptions?: DashboardClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const { user_id: userId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `v1/dashboard/members/${core.url.encodePathParam(userId)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new OmnidapterApi.UnprocessableEntityError(
                        _response.error.body as OmnidapterApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.OmnidapterApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "DELETE",
            "/v1/dashboard/members/{user_id}",
        );
    }

    /**
     * @param {DashboardClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.dashboard.listApiKeys()
     */
    public listApiKeys(requestOptions?: DashboardClient.RequestOptions): core.HttpResponsePromise<unknown> {
        return core.HttpResponsePromise.fromPromise(this.__listApiKeys(requestOptions));
    }

    private async __listApiKeys(
        requestOptions?: DashboardClient.RequestOptions,
    ): Promise<core.WithRawResponse<unknown>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "v1/dashboard/api-keys",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.OmnidapterApiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/v1/dashboard/api-keys");
    }

    /**
     * @param {OmnidapterApi.CreateApiKeyRequest} request
     * @param {DashboardClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link OmnidapterApi.UnprocessableEntityError}
     *
     * @example
     *     await client.dashboard.createApiKey({
     *         name: "name"
     *     })
     */
    public createApiKey(
        request: OmnidapterApi.CreateApiKeyRequest,
        requestOptions?: DashboardClient.RequestOptions,
    ): core.HttpResponsePromise<unknown> {
        return core.HttpResponsePromise.fromPromise(this.__createApiKey(request, requestOptions));
    }

    private async __createApiKey(
        request: OmnidapterApi.CreateApiKeyRequest,
        requestOptions?: DashboardClient.RequestOptions,
    ): Promise<core.WithRawResponse<unknown>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "v1/dashboard/api-keys",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new OmnidapterApi.UnprocessableEntityError(
                        _response.error.body as OmnidapterApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.OmnidapterApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/v1/dashboard/api-keys");
    }

    /**
     * @param {OmnidapterApi.RevokeApiKeyV1DashboardApiKeysKeyIdDeleteRequest} request
     * @param {DashboardClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link OmnidapterApi.UnprocessableEntityError}
     *
     * @example
     *     await client.dashboard.revokeApiKey({
     *         key_id: "key_id"
     *     })
     */
    public revokeApiKey(
        request: OmnidapterApi.RevokeApiKeyV1DashboardApiKeysKeyIdDeleteRequest,
        requestOptions?: DashboardClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__revokeApiKey(request, requestOptions));
    }

    private async __revokeApiKey(
        request: OmnidapterApi.RevokeApiKeyV1DashboardApiKeysKeyIdDeleteRequest,
        requestOptions?: DashboardClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const { key_id: keyId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `v1/dashboard/api-keys/${core.url.encodePathParam(keyId)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new OmnidapterApi.UnprocessableEntityError(
                        _response.error.body as OmnidapterApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.OmnidapterApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "DELETE",
            "/v1/dashboard/api-keys/{key_id}",
        );
    }

    /**
     * @param {DashboardClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.dashboard.listConnections()
     */
    public listConnections(requestOptions?: DashboardClient.RequestOptions): core.HttpResponsePromise<unknown> {
        return core.HttpResponsePromise.fromPromise(this.__listConnections(requestOptions));
    }

    private async __listConnections(
        requestOptions?: DashboardClient.RequestOptions,
    ): Promise<core.WithRawResponse<unknown>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "v1/dashboard/connections",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.OmnidapterApiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/v1/dashboard/connections");
    }

    /**
     * @param {OmnidapterApi.RevokeConnectionV1DashboardConnectionsConnectionIdDeleteRequest} request
     * @param {DashboardClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link OmnidapterApi.UnprocessableEntityError}
     *
     * @example
     *     await client.dashboard.revokeConnection({
     *         connection_id: "connection_id"
     *     })
     */
    public revokeConnection(
        request: OmnidapterApi.RevokeConnectionV1DashboardConnectionsConnectionIdDeleteRequest,
        requestOptions?: DashboardClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__revokeConnection(request, requestOptions));
    }

    private async __revokeConnection(
        request: OmnidapterApi.RevokeConnectionV1DashboardConnectionsConnectionIdDeleteRequest,
        requestOptions?: DashboardClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const { connection_id: connectionId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `v1/dashboard/connections/${core.url.encodePathParam(connectionId)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new OmnidapterApi.UnprocessableEntityError(
                        _response.error.body as OmnidapterApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.OmnidapterApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "DELETE",
            "/v1/dashboard/connections/{connection_id}",
        );
    }

    /**
     * @param {DashboardClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.dashboard.listProviderConfigs()
     */
    public listProviderConfigs(requestOptions?: DashboardClient.RequestOptions): core.HttpResponsePromise<unknown> {
        return core.HttpResponsePromise.fromPromise(this.__listProviderConfigs(requestOptions));
    }

    private async __listProviderConfigs(
        requestOptions?: DashboardClient.RequestOptions,
    ): Promise<core.WithRawResponse<unknown>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "v1/dashboard/provider-configs",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.OmnidapterApiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/v1/dashboard/provider-configs",
        );
    }

    /**
     * @param {OmnidapterApi.UpsertProviderConfigV1DashboardProviderConfigsProviderKeyPutRequest} request
     * @param {DashboardClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link OmnidapterApi.UnprocessableEntityError}
     *
     * @example
     *     await client.dashboard.upsertProviderConfig({
     *         provider_key: "provider_key",
     *         body: {
     *             client_id: "client_id",
     *             client_secret: "client_secret"
     *         }
     *     })
     */
    public upsertProviderConfig(
        request: OmnidapterApi.UpsertProviderConfigV1DashboardProviderConfigsProviderKeyPutRequest,
        requestOptions?: DashboardClient.RequestOptions,
    ): core.HttpResponsePromise<unknown> {
        return core.HttpResponsePromise.fromPromise(this.__upsertProviderConfig(request, requestOptions));
    }

    private async __upsertProviderConfig(
        request: OmnidapterApi.UpsertProviderConfigV1DashboardProviderConfigsProviderKeyPutRequest,
        requestOptions?: DashboardClient.RequestOptions,
    ): Promise<core.WithRawResponse<unknown>> {
        const { provider_key: providerKey, body: _body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `v1/dashboard/provider-configs/${core.url.encodePathParam(providerKey)}`,
            ),
            method: "PUT",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new OmnidapterApi.UnprocessableEntityError(
                        _response.error.body as OmnidapterApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.OmnidapterApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "PUT",
            "/v1/dashboard/provider-configs/{provider_key}",
        );
    }

    /**
     * @param {OmnidapterApi.DeleteProviderConfigV1DashboardProviderConfigsProviderKeyDeleteRequest} request
     * @param {DashboardClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link OmnidapterApi.UnprocessableEntityError}
     *
     * @example
     *     await client.dashboard.deleteProviderConfig({
     *         provider_key: "provider_key"
     *     })
     */
    public deleteProviderConfig(
        request: OmnidapterApi.DeleteProviderConfigV1DashboardProviderConfigsProviderKeyDeleteRequest,
        requestOptions?: DashboardClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__deleteProviderConfig(request, requestOptions));
    }

    private async __deleteProviderConfig(
        request: OmnidapterApi.DeleteProviderConfigV1DashboardProviderConfigsProviderKeyDeleteRequest,
        requestOptions?: DashboardClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const { provider_key: providerKey } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `v1/dashboard/provider-configs/${core.url.encodePathParam(providerKey)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new OmnidapterApi.UnprocessableEntityError(
                        _response.error.body as OmnidapterApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.OmnidapterApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "DELETE",
            "/v1/dashboard/provider-configs/{provider_key}",
        );
    }

    /**
     * @param {DashboardClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.dashboard.getUsage()
     */
    public getUsage(requestOptions?: DashboardClient.RequestOptions): core.HttpResponsePromise<unknown> {
        return core.HttpResponsePromise.fromPromise(this.__getUsage(requestOptions));
    }

    private async __getUsage(requestOptions?: DashboardClient.RequestOptions): Promise<core.WithRawResponse<unknown>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "v1/dashboard/usage",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.OmnidapterApiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/v1/dashboard/usage");
    }
}
