"""Hosted extensions — link tokens, provider config, and connect

Revision ID: hosted_0002
Revises: hosted_0001
Create Date: 2026-03-26 14:10:15.571739

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "hosted_0002"
down_revision: str | Sequence[str] | None = "hosted_0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hosted_link_tokens",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.String(length=255), nullable=False),
        sa.Column("token_prefix", sa.String(length=20), nullable=False),
        sa.Column("end_user_id", sa.String(length=255), nullable=True),
        sa.Column("allowed_providers", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("redirect_uri", sa.Text(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("connection_id", sa.UUID(), nullable=True),
        sa.Column("locked_provider_key", sa.String(length=50), nullable=True),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_index("ix_hosted_link_tokens_token_prefix", "hosted_link_tokens", ["token_prefix"])
    op.create_index(
        "ix_hosted_link_tokens_tenant_is_active", "hosted_link_tokens", ["tenant_id", "is_active"]
    )
    # server_default=true so existing rows are enabled; dropped after backfill
    op.add_column(
        "hosted_provider_configs",
        sa.Column("is_enabled", sa.Boolean(), nullable=False, server_default=sa.true()),
    )
    op.alter_column("hosted_provider_configs", "is_enabled", server_default=None)
    op.drop_constraint(
        op.f("hosted_connection_owners_connection_id_fkey"),
        "hosted_connection_owners",
        type_="foreignkey",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        op.f("hosted_connection_owners_connection_id_fkey"),
        "hosted_connection_owners",
        "connections",
        ["connection_id"],
        ["id"],
    )
    op.drop_column("hosted_provider_configs", "is_enabled")
    op.drop_index("ix_hosted_link_tokens_tenant_is_active", "hosted_link_tokens")
    op.drop_index("ix_hosted_link_tokens_token_prefix", "hosted_link_tokens")
    op.drop_table("hosted_link_tokens")
    # ### end Alembic commands ###
