# This file was auto-generated by Fern from our API Definition.

import typing

AttendeeStatus = typing.Union[
    typing.Literal["accepted", "declined", "tentative", "needs_action", "unknown"],
    typing.Any,
]
