# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
from .conference_entry_point import ConferenceEntryPoint
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class ConferenceData(UniversalBaseModel):
    """
    Conference/video call information attached to an event.
    """

    conference_id: typing.Optional[str] = None
    conference_solution_name: typing.Optional[str] = None
    entry_points: typing.Optional[typing.List[ConferenceEntryPoint]] = None
    join_url: typing.Optional[str] = None
    provider_data: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow", frozen=True
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
