# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
from .recurrence_original_start_time import RecurrenceOriginalStartTime
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class Recurrence(UniversalBaseModel):
    """
    Recurrence information for recurring events.

    `rules` contains RRULE/EXRULE/RDATE/EXDATE strings (RFC 5545 format).
    """

    rules: typing.Optional[typing.List[str]] = None
    recurring_event_id: typing.Optional[str] = None
    original_start_time: typing.Optional[RecurrenceOriginalStartTime] = None
    provider_data: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow", frozen=True
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
