// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         provider_key: "provider_key"
 *     }
 */
export interface GetProviderConfigV1ProviderConfigsProviderKeyGetRequest {
    provider_key: string;
}
