// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         provider_key: "provider_key",
 *         is_enabled: true
 *     }
 */
export interface PatchProviderConfigRequest {
    provider_key: string;
    is_enabled: boolean;
}
