// This file was auto-generated by Fern from our API Definition.

import type * as OmnidapterApi from "../index.js";

/**
 * Conference/video call information attached to an event.
 */
export interface ConferenceData {
    conference_id?: (string | null) | undefined;
    conference_solution_name?: (string | null) | undefined;
    entry_points?: OmnidapterApi.ConferenceEntryPoint[] | undefined;
    join_url?: (string | null) | undefined;
    provider_data?: (Record<string, unknown> | null) | undefined;
}
