// This file was auto-generated by Fern from our API Definition.

/**
 * A single entry point for a conference (e.g., video URL, phone dial-in).
 */
export interface ConferenceEntryPoint {
    entry_point_type: string;
    uri: string;
    label?: (string | null) | undefined;
    pin?: (string | null) | undefined;
    provider_data?: (Record<string, unknown> | null) | undefined;
}
