// This file was auto-generated by Fern from our API Definition.

export const EventStatus = {
    Confirmed: "confirmed",
    Tentative: "tentative",
    Cancelled: "cancelled",
    Unknown: "unknown",
} as const;
export type EventStatus = (typeof EventStatus)[keyof typeof EventStatus];
