// This file was auto-generated by Fern from our API Definition.

import type * as OmnidapterApi from "../index.js";

export interface HttpValidationError {
    detail?: OmnidapterApi.ValidationError[] | undefined;
}
