// This file was auto-generated by Fern from our API Definition.

/**
 * Recurrence information for recurring events.
 *
 * `rules` contains RRULE/EXRULE/RDATE/EXDATE strings (RFC 5545 format).
 */
export interface Recurrence {
    rules?: string[] | undefined;
    recurring_event_id?: (string | null) | undefined;
    original_start_time?: (Recurrence.OriginalStartTime | null) | undefined;
    provider_data?: (Record<string, unknown> | null) | undefined;
}

export namespace Recurrence {
    export type OriginalStartTime = string | string;
}
