// This file was auto-generated by Fern from our API Definition.

/**
 * A single reminder override for an event.
 */
export interface ReminderOverride {
    method: string;
    minutes_before: number;
}
