// This file was auto-generated by Fern from our API Definition.

export interface UpsertProviderConfigRequest {
    client_id: string;
    client_secret: string;
    scopes?: (string[] | null) | undefined;
}
