// This file was auto-generated by Fern from our API Definition.

import type * as OmnidapterApi from "../../../../index.js";

/**
 * @example
 *     {
 *         connection_id: "connection_id",
 *         calendar_id: "calendar_id",
 *         summary: "summary",
 *         start: "2024-01-15T09:30:00Z",
 *         end: "2024-01-15T09:30:00Z"
 *     }
 */
export interface CreateEventRequest {
    connection_id: string;
    calendar_id: string;
    summary: string;
    start: CreateEventRequest.Start;
    end: CreateEventRequest.End;
    all_day?: boolean;
    timezone?: string | null;
    description?: string | null;
    location?: string | null;
    attendees?: OmnidapterApi.Attendee[];
    recurrence?: OmnidapterApi.Recurrence | null;
    conference_data?: OmnidapterApi.ConferenceData | null;
    reminders?: OmnidapterApi.Reminder | null;
    visibility?: string | null;
    status?: OmnidapterApi.EventStatus | null;
    extra?: Record<string, unknown>;
}

export namespace CreateEventRequest {
    export type Start = string | string;
    export type End = string | string;
}
