// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         connection_id: "connection_id",
 *         summary: "summary"
 *     }
 */
export interface CreateCalendarRequest {
    connection_id: string;
    summary: string;
    description?: string | null;
    timezone?: string | null;
    background_color?: string | null;
    foreground_color?: string | null;
    extra?: Record<string, unknown>;
}
