// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         connection_id: "connection_id",
 *         calendar_id: "calendar_id"
 *     }
 */
export interface DeleteCalendarV1ConnectionsConnectionIdCalendarsCalendarIdDeleteRequest {
    connection_id: string;
    calendar_id: string;
}
