// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         connection_id: "connection_id",
 *         calendar_id: "calendar_id"
 *     }
 */
export interface UpdateCalendarRequest {
    connection_id: string;
    calendar_id: string;
    summary?: string | null;
    description?: string | null;
    timezone?: string | null;
    background_color?: string | null;
    foreground_color?: string | null;
    extra?: Record<string, unknown>;
}
