# coding: utf-8

# flake8: noqa

"""
    Omnidapter Server

    Self-hosted REST API wrapping the Omnidapter calendar integration library

    The version of the OpenAPI document: 0.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "CalendarApi",
    "ConnectionsApi",
    "LinkTokensApi",
    "ProvidersApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "Attendee",
    "AttendeeStatus",
    "ConferenceData",
    "ConferenceEntryPoint",
    "ConnectCreateConnectionRequest",
    "ConnectSessionRequest",
    "CreateCalendarRequest",
    "CreateConnectionRequest",
    "CreateEventRequest",
    "CreateLinkTokenRequest",
    "End",
    "End1",
    "EventStatus",
    "HTTPValidationError",
    "LocationInner",
    "OriginalStartTime",
    "ReauthorizeConnectionRequest",
    "Recurrence",
    "Reminder",
    "ReminderOverride",
    "Start",
    "Start1",
    "UpdateCalendarRequest",
    "UpdateEventRequest",
    "ValidationError",
]

# import apis into sdk package
from omnidapter_sdk.api.calendar_api import CalendarApi as CalendarApi
from omnidapter_sdk.api.connections_api import ConnectionsApi as ConnectionsApi
from omnidapter_sdk.api.link_tokens_api import LinkTokensApi as LinkTokensApi
from omnidapter_sdk.api.providers_api import ProvidersApi as ProvidersApi

# import ApiClient
from omnidapter_sdk.api_response import ApiResponse as ApiResponse
from omnidapter_sdk.api_client import ApiClient as ApiClient
from omnidapter_sdk.configuration import Configuration as Configuration
from omnidapter_sdk.exceptions import OpenApiException as OpenApiException
from omnidapter_sdk.exceptions import ApiTypeError as ApiTypeError
from omnidapter_sdk.exceptions import ApiValueError as ApiValueError
from omnidapter_sdk.exceptions import ApiKeyError as ApiKeyError
from omnidapter_sdk.exceptions import ApiAttributeError as ApiAttributeError
from omnidapter_sdk.exceptions import ApiException as ApiException

# import models into sdk package
from omnidapter_sdk.models.attendee import Attendee as Attendee
from omnidapter_sdk.models.attendee_status import AttendeeStatus as AttendeeStatus
from omnidapter_sdk.models.conference_data import ConferenceData as ConferenceData
from omnidapter_sdk.models.conference_entry_point import ConferenceEntryPoint as ConferenceEntryPoint
from omnidapter_sdk.models.connect_create_connection_request import ConnectCreateConnectionRequest as ConnectCreateConnectionRequest
from omnidapter_sdk.models.connect_session_request import ConnectSessionRequest as ConnectSessionRequest
from omnidapter_sdk.models.create_calendar_request import CreateCalendarRequest as CreateCalendarRequest
from omnidapter_sdk.models.create_connection_request import CreateConnectionRequest as CreateConnectionRequest
from omnidapter_sdk.models.create_event_request import CreateEventRequest as CreateEventRequest
from omnidapter_sdk.models.create_link_token_request import CreateLinkTokenRequest as CreateLinkTokenRequest
from omnidapter_sdk.models.end import End as End
from omnidapter_sdk.models.end1 import End1 as End1
from omnidapter_sdk.models.event_status import EventStatus as EventStatus
from omnidapter_sdk.models.http_validation_error import HTTPValidationError as HTTPValidationError
from omnidapter_sdk.models.location_inner import LocationInner as LocationInner
from omnidapter_sdk.models.original_start_time import OriginalStartTime as OriginalStartTime
from omnidapter_sdk.models.reauthorize_connection_request import ReauthorizeConnectionRequest as ReauthorizeConnectionRequest
from omnidapter_sdk.models.recurrence import Recurrence as Recurrence
from omnidapter_sdk.models.reminder import Reminder as Reminder
from omnidapter_sdk.models.reminder_override import ReminderOverride as ReminderOverride
from omnidapter_sdk.models.start import Start as Start
from omnidapter_sdk.models.start1 import Start1 as Start1
from omnidapter_sdk.models.update_calendar_request import UpdateCalendarRequest as UpdateCalendarRequest
from omnidapter_sdk.models.update_event_request import UpdateEventRequest as UpdateEventRequest
from omnidapter_sdk.models.validation_error import ValidationError as ValidationError

