// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         key_id: "key_id"
 *     }
 */
export interface RevokeApiKeyV1DashboardApiKeysKeyIdDeleteRequest {
    key_id: string;
}
