import React from "react";

export const getStyles = (): Record<string, React.CSSProperties> => ({
  root: {
    height: "100vh",
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
  },
  header: {
    background: "var(--header-bg)",
    color: "#fff",
    padding: "20px 24px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  title: {
    fontSize: 20,
    fontWeight: 600,
    letterSpacing: -0.3,
  },
  subtitle: {
    fontSize: 13,
    color: "var(--text-tertiary)",
    marginTop: 2,
  },
  themeBtn: {
    background: "var(--theme-btn-bg)",
    border: "none",
    color: "var(--theme-btn-color)",
    cursor: "pointer",
    fontSize: 18,
    lineHeight: 1,
    padding: 4,
    width: 32,
    height: 32,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 6,
  },
  body: {
    flex: 1,
    display: "grid",
    gap: 0,
    minHeight: 0,
  },
  left: {
    padding: 24,
    borderRight: "1px solid var(--border)",
    background: "var(--bg-main)",
    display: "flex",
    flexDirection: "column",
    gap: 4,
    minWidth: 0,
    overflowY: "auto",
  },
  right: {
    display: "flex",
    flexDirection: "column",
    background: "var(--bg-secondary)",
    minHeight: 0,
    overflow: "hidden",
  },
  section: {
    marginBottom: 24,
  },
  sectionTitle: {
    fontSize: 11,
    fontWeight: 600,
    textTransform: "uppercase",
    letterSpacing: 0.8,
    color: "var(--text-secondary)",
    marginBottom: 10,
  },
  tabs: {
    display: "flex",
    gap: 6,
    marginBottom: 10,
  },
  tab: {
    flex: 1,
    padding: "7px 0",
    fontSize: 13,
    fontWeight: 500,
    border: "1px solid var(--border)",
    borderRadius: 6,
    background: "var(--bg-main)",
    cursor: "pointer",
    color: "var(--text-secondary)",
    transition: "all 0.1s",
  },
  tabActive: {
    background: "var(--btn-active-bg)",
    color: "var(--btn-active-text)",
    border: "1px solid var(--btn-active-bg)",
  },
  modeDesc: {
    fontSize: 12,
    color: "var(--text-secondary)",
    lineHeight: 1.5,
  },
  warnIcon: {
    position: "absolute",
    right: 8,
    top: "50%",
    transform: "translateY(-50%)",
    fontSize: 13,
    color: "var(--warn-text)",
    cursor: "default",
    lineHeight: 1,
  },
  warnTooltip: {
    position: "absolute",
    right: 0,
    bottom: "calc(100% + 6px)",
    background: "var(--warn-bg)",
    border: "1px solid var(--warn-border)",
    color: "var(--warn-text)",
    borderRadius: 6,
    padding: "6px 10px",
    fontSize: 11,
    lineHeight: 1.5,
    width: 240,
    zIndex: 10,
    boxShadow: "0 2px 8px rgba(0,0,0,0.12)",
  },
  fieldLabel: {
    display: "block",
    fontSize: 12,
    fontWeight: 500,
    color: "var(--label)",
    marginBottom: 5,
  },
  input: {
    width: "100%",
    boxSizing: "border-box",
    padding: "8px 10px",
    fontSize: 13,
    border: "1px solid var(--input-border)",
    borderRadius: 6,
    outline: "none",
    background: "var(--bg-main)",
    color: "var(--text)",
    fontFamily: "inherit",
  },
  connectBtn: {
    marginTop: "auto",
    padding: "10px 0",
    fontSize: 14,
    fontWeight: 600,
    background: "var(--btn-active-bg)",
    color: "var(--btn-active-text)",
    border: "none",
    borderRadius: 8,
    cursor: "pointer",
    width: "100%",
  },
  connectBtnDisabled: {
    opacity: 0.5,
    cursor: "not-allowed",
  },
  logHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "12px 24px",
    borderBottom: "1px solid var(--border)",
    background: "var(--bg-main)",
  },
  clearBtn: {
    fontSize: 12,
    color: "var(--text-secondary)",
    background: "none",
    border: "1px solid var(--border)",
    borderRadius: 4,
    padding: "3px 8px",
    cursor: "pointer",
  },
  logPanel: {
    flex: 1,
    overflowY: "auto",
    padding: "12px 24px",
    display: "flex",
    flexDirection: "column",
    gap: 6,
  },
  logEmpty: {
    fontSize: 13,
    color: "var(--text-tertiary)",
    marginTop: 8,
  },
  logEntry: {
    display: "flex",
    gap: 10,
    alignItems: "flex-start",
    borderLeft: "3px solid var(--text-tertiary)",
    paddingLeft: 10,
    paddingTop: 3,
    paddingBottom: 3,
  },
  logTime: {
    fontSize: 11,
    color: "var(--text-tertiary)",
    fontVariantNumeric: "tabular-nums",
    flexShrink: 0,
    paddingTop: 1,
    fontFamily: "monospace",
  },
  logContent: {
    display: "flex",
    flexDirection: "column",
    gap: 2,
    fontSize: 13,
  },
  logDetail: {
    fontSize: 11,
    color: "var(--text-secondary)",
    fontFamily: "monospace",
  },
  overlay: {
    position: "fixed",
    inset: 0,
    background: "rgba(0,0,0,0.5)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 100,
  },
  modal: {
    background: "var(--bg-main)",
    borderRadius: 12,
    overflow: "hidden",
    boxShadow: "0 20px 60px rgba(0,0,0,0.3)",
    display: "flex",
    flexDirection: "column",
    width: 480,
  },
  modalHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "12px 16px",
    borderBottom: "1px solid var(--border)",
  },
  modalTitle: {
    fontSize: 14,
    fontWeight: 600,
    color: "var(--text)",
  },
  modalClose: {
    background: "none",
    border: "none",
    cursor: "pointer",
    fontSize: 16,
    color: "var(--text-secondary)",
    lineHeight: 1,
    padding: 4,
  },
  iframe: {
    width: "100%",
    height: 600,
    border: "none",
    display: "block",
  },
  iframeCallback: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    height: "100vh",
    fontFamily: "system-ui",
  },
});
