# coding: utf-8

# flake8: noqa
"""
    Omnidapter Server

    Self-hosted REST API wrapping the Omnidapter calendar integration library

    The version of the OpenAPI document: 0.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from omnidapter_sdk.models.attendee import Attendee
from omnidapter_sdk.models.attendee_status import AttendeeStatus
from omnidapter_sdk.models.conference_data import ConferenceData
from omnidapter_sdk.models.conference_entry_point import ConferenceEntryPoint
from omnidapter_sdk.models.connect_create_connection_request import ConnectCreateConnectionRequest
from omnidapter_sdk.models.connect_session_request import ConnectSessionRequest
from omnidapter_sdk.models.create_calendar_request import CreateCalendarRequest
from omnidapter_sdk.models.create_connection_request import CreateConnectionRequest
from omnidapter_sdk.models.create_event_request import CreateEventRequest
from omnidapter_sdk.models.create_link_token_request import CreateLinkTokenRequest
from omnidapter_sdk.models.end import End
from omnidapter_sdk.models.end1 import End1
from omnidapter_sdk.models.event_status import EventStatus
from omnidapter_sdk.models.http_validation_error import HTTPValidationError
from omnidapter_sdk.models.location_inner import LocationInner
from omnidapter_sdk.models.original_start_time import OriginalStartTime
from omnidapter_sdk.models.reauthorize_connection_request import ReauthorizeConnectionRequest
from omnidapter_sdk.models.recurrence import Recurrence
from omnidapter_sdk.models.reminder import Reminder
from omnidapter_sdk.models.reminder_override import ReminderOverride
from omnidapter_sdk.models.start import Start
from omnidapter_sdk.models.start1 import Start1
from omnidapter_sdk.models.update_calendar_request import UpdateCalendarRequest
from omnidapter_sdk.models.update_event_request import UpdateEventRequest
from omnidapter_sdk.models.validation_error import ValidationError

