# coding: utf-8

"""
    Omnidapter Server

    Self-hosted REST API wrapping the Omnidapter calendar integration library

    The version of the OpenAPI document: 0.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from omnidapter_sdk.models.attendee_status import AttendeeStatus
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Attendee(BaseModel):
    """
    An event attendee.
    """ # noqa: E501
    email: StrictStr
    display_name: Optional[StrictStr] = None
    status: Optional[AttendeeStatus] = None
    is_organizer: Optional[StrictBool] = False
    is_self: Optional[StrictBool] = False
    is_resource: Optional[StrictBool] = False
    optional: Optional[StrictBool] = False
    comment: Optional[StrictStr] = None
    provider_data: Optional[Dict[str, Any]] = None
    __properties: ClassVar[List[str]] = ["email", "display_name", "status", "is_organizer", "is_self", "is_resource", "optional", "comment", "provider_data"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Attendee from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if display_name (nullable) is None
        # and model_fields_set contains the field
        if self.display_name is None and "display_name" in self.model_fields_set:
            _dict['display_name'] = None

        # set to None if comment (nullable) is None
        # and model_fields_set contains the field
        if self.comment is None and "comment" in self.model_fields_set:
            _dict['comment'] = None

        # set to None if provider_data (nullable) is None
        # and model_fields_set contains the field
        if self.provider_data is None and "provider_data" in self.model_fields_set:
            _dict['provider_data'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Attendee from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "email": obj.get("email"),
            "display_name": obj.get("display_name"),
            "status": obj.get("status"),
            "is_organizer": obj.get("is_organizer") if obj.get("is_organizer") is not None else False,
            "is_self": obj.get("is_self") if obj.get("is_self") is not None else False,
            "is_resource": obj.get("is_resource") if obj.get("is_resource") is not None else False,
            "optional": obj.get("optional") if obj.get("optional") is not None else False,
            "comment": obj.get("comment"),
            "provider_data": obj.get("provider_data")
        })
        return _obj


