# coding: utf-8

"""
    Omnidapter Server

    Self-hosted REST API wrapping the Omnidapter calendar integration library

    The version of the OpenAPI document: 0.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class AttendeeStatus(str, Enum):
    """
    AttendeeStatus
    """

    """
    allowed enum values
    """
    ACCEPTED = 'accepted'
    DECLINED = 'declined'
    TENTATIVE = 'tentative'
    NEEDS_ACTION = 'needs_action'
    UNKNOWN = 'unknown'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AttendeeStatus from a JSON string"""
        return cls(json.loads(json_str))


