# coding: utf-8

"""
    Omnidapter Server

    Self-hosted REST API wrapping the Omnidapter calendar integration library

    The version of the OpenAPI document: 0.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from uuid import UUID
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CreateLinkTokenRequest(BaseModel):
    """
    CreateLinkTokenRequest
    """ # noqa: E501
    end_user_id: Optional[StrictStr] = None
    allowed_providers: Optional[List[StrictStr]] = None
    redirect_uri: Optional[StrictStr] = None
    ttl_seconds: Optional[Annotated[int, Field(le=86400, strict=True, ge=60)]] = None
    connection_id: Optional[UUID] = None
    __properties: ClassVar[List[str]] = ["end_user_id", "allowed_providers", "redirect_uri", "ttl_seconds", "connection_id"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateLinkTokenRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if end_user_id (nullable) is None
        # and model_fields_set contains the field
        if self.end_user_id is None and "end_user_id" in self.model_fields_set:
            _dict['end_user_id'] = None

        # set to None if allowed_providers (nullable) is None
        # and model_fields_set contains the field
        if self.allowed_providers is None and "allowed_providers" in self.model_fields_set:
            _dict['allowed_providers'] = None

        # set to None if redirect_uri (nullable) is None
        # and model_fields_set contains the field
        if self.redirect_uri is None and "redirect_uri" in self.model_fields_set:
            _dict['redirect_uri'] = None

        # set to None if ttl_seconds (nullable) is None
        # and model_fields_set contains the field
        if self.ttl_seconds is None and "ttl_seconds" in self.model_fields_set:
            _dict['ttl_seconds'] = None

        # set to None if connection_id (nullable) is None
        # and model_fields_set contains the field
        if self.connection_id is None and "connection_id" in self.model_fields_set:
            _dict['connection_id'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateLinkTokenRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "end_user_id": obj.get("end_user_id"),
            "allowed_providers": obj.get("allowed_providers"),
            "redirect_uri": obj.get("redirect_uri"),
            "ttl_seconds": obj.get("ttl_seconds"),
            "connection_id": obj.get("connection_id")
        })
        return _obj


