# coding: utf-8

"""
    Omnidapter Server

    Self-hosted REST API wrapping the Omnidapter calendar integration library

    The version of the OpenAPI document: 0.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from omnidapter_sdk.models.original_start_time import OriginalStartTime
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Recurrence(BaseModel):
    """
    Recurrence information for recurring events.  `rules` contains RRULE/EXRULE/RDATE/EXDATE strings (RFC 5545 format).
    """ # noqa: E501
    rules: Optional[List[StrictStr]] = None
    recurring_event_id: Optional[StrictStr] = None
    original_start_time: Optional[OriginalStartTime] = None
    provider_data: Optional[Dict[str, Any]] = None
    __properties: ClassVar[List[str]] = ["rules", "recurring_event_id", "original_start_time", "provider_data"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Recurrence from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of original_start_time
        if self.original_start_time:
            _dict['original_start_time'] = self.original_start_time.to_dict()
        # set to None if recurring_event_id (nullable) is None
        # and model_fields_set contains the field
        if self.recurring_event_id is None and "recurring_event_id" in self.model_fields_set:
            _dict['recurring_event_id'] = None

        # set to None if original_start_time (nullable) is None
        # and model_fields_set contains the field
        if self.original_start_time is None and "original_start_time" in self.model_fields_set:
            _dict['original_start_time'] = None

        # set to None if provider_data (nullable) is None
        # and model_fields_set contains the field
        if self.provider_data is None and "provider_data" in self.model_fields_set:
            _dict['provider_data'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Recurrence from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "rules": obj.get("rules"),
            "recurring_event_id": obj.get("recurring_event_id"),
            "original_start_time": OriginalStartTime.from_dict(obj["original_start_time"]) if obj.get("original_start_time") is not None else None,
            "provider_data": obj.get("provider_data")
        })
        return _obj


