# coding: utf-8

"""
    Omnidapter Server

    Self-hosted REST API wrapping the Omnidapter calendar integration library

    The version of the OpenAPI document: 0.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from omnidapter_sdk.models.attendee import Attendee
from omnidapter_sdk.models.conference_data import ConferenceData
from omnidapter_sdk.models.end1 import End1
from omnidapter_sdk.models.event_status import EventStatus
from omnidapter_sdk.models.recurrence import Recurrence
from omnidapter_sdk.models.reminder import Reminder
from omnidapter_sdk.models.start1 import Start1
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class UpdateEventRequest(BaseModel):
    """
    Request model for updating a calendar event.  When used via the REST API, ``calendar_id`` and ``event_id`` are injected from URL path parameters.  When using the Python library directly, callers must supply non-empty values for both fields.
    """ # noqa: E501
    calendar_id: Optional[StrictStr] = ''
    event_id: Optional[StrictStr] = ''
    summary: Optional[StrictStr] = None
    start: Optional[Start1] = None
    end: Optional[End1] = None
    all_day: Optional[StrictBool] = None
    timezone: Optional[StrictStr] = None
    description: Optional[StrictStr] = None
    location: Optional[StrictStr] = None
    attendees: Optional[List[Attendee]] = None
    recurrence: Optional[Recurrence] = None
    conference_data: Optional[ConferenceData] = None
    reminders: Optional[Reminder] = None
    visibility: Optional[StrictStr] = None
    status: Optional[EventStatus] = None
    extra: Optional[Dict[str, Any]] = None
    __properties: ClassVar[List[str]] = ["calendar_id", "event_id", "summary", "start", "end", "all_day", "timezone", "description", "location", "attendees", "recurrence", "conference_data", "reminders", "visibility", "status", "extra"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UpdateEventRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of start
        if self.start:
            _dict['start'] = self.start.to_dict()
        # override the default output from pydantic by calling `to_dict()` of end
        if self.end:
            _dict['end'] = self.end.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in attendees (list)
        _items = []
        if self.attendees:
            for _item_attendees in self.attendees:
                if _item_attendees:
                    _items.append(_item_attendees.to_dict())
            _dict['attendees'] = _items
        # override the default output from pydantic by calling `to_dict()` of recurrence
        if self.recurrence:
            _dict['recurrence'] = self.recurrence.to_dict()
        # override the default output from pydantic by calling `to_dict()` of conference_data
        if self.conference_data:
            _dict['conference_data'] = self.conference_data.to_dict()
        # override the default output from pydantic by calling `to_dict()` of reminders
        if self.reminders:
            _dict['reminders'] = self.reminders.to_dict()
        # set to None if summary (nullable) is None
        # and model_fields_set contains the field
        if self.summary is None and "summary" in self.model_fields_set:
            _dict['summary'] = None

        # set to None if start (nullable) is None
        # and model_fields_set contains the field
        if self.start is None and "start" in self.model_fields_set:
            _dict['start'] = None

        # set to None if end (nullable) is None
        # and model_fields_set contains the field
        if self.end is None and "end" in self.model_fields_set:
            _dict['end'] = None

        # set to None if all_day (nullable) is None
        # and model_fields_set contains the field
        if self.all_day is None and "all_day" in self.model_fields_set:
            _dict['all_day'] = None

        # set to None if timezone (nullable) is None
        # and model_fields_set contains the field
        if self.timezone is None and "timezone" in self.model_fields_set:
            _dict['timezone'] = None

        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if location (nullable) is None
        # and model_fields_set contains the field
        if self.location is None and "location" in self.model_fields_set:
            _dict['location'] = None

        # set to None if attendees (nullable) is None
        # and model_fields_set contains the field
        if self.attendees is None and "attendees" in self.model_fields_set:
            _dict['attendees'] = None

        # set to None if recurrence (nullable) is None
        # and model_fields_set contains the field
        if self.recurrence is None and "recurrence" in self.model_fields_set:
            _dict['recurrence'] = None

        # set to None if conference_data (nullable) is None
        # and model_fields_set contains the field
        if self.conference_data is None and "conference_data" in self.model_fields_set:
            _dict['conference_data'] = None

        # set to None if reminders (nullable) is None
        # and model_fields_set contains the field
        if self.reminders is None and "reminders" in self.model_fields_set:
            _dict['reminders'] = None

        # set to None if visibility (nullable) is None
        # and model_fields_set contains the field
        if self.visibility is None and "visibility" in self.model_fields_set:
            _dict['visibility'] = None

        # set to None if status (nullable) is None
        # and model_fields_set contains the field
        if self.status is None and "status" in self.model_fields_set:
            _dict['status'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UpdateEventRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "calendar_id": obj.get("calendar_id") if obj.get("calendar_id") is not None else '',
            "event_id": obj.get("event_id") if obj.get("event_id") is not None else '',
            "summary": obj.get("summary"),
            "start": Start1.from_dict(obj["start"]) if obj.get("start") is not None else None,
            "end": End1.from_dict(obj["end"]) if obj.get("end") is not None else None,
            "all_day": obj.get("all_day"),
            "timezone": obj.get("timezone"),
            "description": obj.get("description"),
            "location": obj.get("location"),
            "attendees": [Attendee.from_dict(_item) for _item in obj["attendees"]] if obj.get("attendees") is not None else None,
            "recurrence": Recurrence.from_dict(obj["recurrence"]) if obj.get("recurrence") is not None else None,
            "conference_data": ConferenceData.from_dict(obj["conference_data"]) if obj.get("conference_data") is not None else None,
            "reminders": Reminder.from_dict(obj["reminders"]) if obj.get("reminders") is not None else None,
            "visibility": obj.get("visibility"),
            "status": obj.get("status"),
            "extra": obj.get("extra")
        })
        return _obj


