// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         provider: "provider",
 *         redirect_url: "redirect_url"
 *     }
 */
export interface CreateConnectionRequest {
    provider: string;
    external_id?: string | null;
    redirect_url: string;
    metadata?: Record<string, unknown> | null;
}
