// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         connection_id: "connection_id"
 *     }
 */
export interface GetConnectionEndpointV1ConnectionsConnectionIdGetRequest {
    connection_id: string;
}
