// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface ListConnectionsV1ConnectionsGetRequest {
    status?: string | null;
    provider?: string | null;
    external_id?: string | null;
    limit?: number;
    offset?: number;
}
