// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         connection_id: "connection_id",
 *         redirect_url: "redirect_url"
 *     }
 */
export interface ReauthorizeConnectionRequest {
    connection_id: string;
    redirect_url: string;
}
