# This file was auto-generated by Fern from our API Definition.

import typing
from ..core.client_wrapper import SyncClientWrapper
from ..core.request_options import RequestOptions
from ..core.jsonable_encoder import jsonable_encoder
from ..core.pydantic_utilities import parse_obj_as
from ..errors.unprocessable_entity_error import UnprocessableEntityError
from ..types.http_validation_error import HttpValidationError
from json.decoder import JSONDecodeError
from ..core.api_error import ApiError
import datetime as dt
from ..core.datetime_utils import serialize_datetime
from .types.create_event_request_start import CreateEventRequestStart
from .types.create_event_request_end import CreateEventRequestEnd
from ..types.attendee import Attendee
from ..types.recurrence import Recurrence
from ..types.conference_data import ConferenceData
from ..types.reminder import Reminder
from ..types.event_status import EventStatus
from ..core.serialization import convert_and_respect_annotation_metadata
from .types.update_event_request_start import UpdateEventRequestStart
from .types.update_event_request_end import UpdateEventRequestEnd
from ..core.client_wrapper import AsyncClientWrapper

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class CalendarClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def list_calendars(
        self,
        connection_id: str,
        *,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Optional[typing.Any]:
        """
        Parameters
        ----------
        connection_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Optional[typing.Any]
            Successful Response

        Examples
        --------
        from omnidapter_sdk import OmnidapterApi

        client = OmnidapterApi(
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )
        client.calendar.list_calendars(
            connection_id="connection_id",
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/connections/{jsonable_encoder(connection_id)}/calendars",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    typing.Optional[typing.Any],
                    parse_obj_as(
                        type_=typing.Optional[typing.Any],  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def create_calendar(
        self,
        connection_id: str,
        *,
        summary: str,
        description: typing.Optional[str] = OMIT,
        timezone: typing.Optional[str] = OMIT,
        background_color: typing.Optional[str] = OMIT,
        foreground_color: typing.Optional[str] = OMIT,
        extra: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Optional[typing.Any]:
        """
        Parameters
        ----------
        connection_id : str

        summary : str

        description : typing.Optional[str]

        timezone : typing.Optional[str]

        background_color : typing.Optional[str]

        foreground_color : typing.Optional[str]

        extra : typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Optional[typing.Any]
            Successful Response

        Examples
        --------
        from omnidapter_sdk import OmnidapterApi

        client = OmnidapterApi(
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )
        client.calendar.create_calendar(
            connection_id="connection_id",
            summary="summary",
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/connections/{jsonable_encoder(connection_id)}/calendars",
            method="POST",
            json={
                "summary": summary,
                "description": description,
                "timezone": timezone,
                "background_color": background_color,
                "foreground_color": foreground_color,
                "extra": extra,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    typing.Optional[typing.Any],
                    parse_obj_as(
                        type_=typing.Optional[typing.Any],  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def get_calendar(
        self,
        connection_id: str,
        calendar_id: str,
        *,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Optional[typing.Any]:
        """
        Parameters
        ----------
        connection_id : str

        calendar_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Optional[typing.Any]
            Successful Response

        Examples
        --------
        from omnidapter_sdk import OmnidapterApi

        client = OmnidapterApi(
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )
        client.calendar.get_calendar(
            connection_id="connection_id",
            calendar_id="calendar_id",
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/connections/{jsonable_encoder(connection_id)}/calendars/{jsonable_encoder(calendar_id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    typing.Optional[typing.Any],
                    parse_obj_as(
                        type_=typing.Optional[typing.Any],  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def delete_calendar(
        self,
        connection_id: str,
        calendar_id: str,
        *,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Parameters
        ----------
        connection_id : str

        calendar_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from omnidapter_sdk import OmnidapterApi

        client = OmnidapterApi(
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )
        client.calendar.delete_calendar(
            connection_id="connection_id",
            calendar_id="calendar_id",
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/connections/{jsonable_encoder(connection_id)}/calendars/{jsonable_encoder(calendar_id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def update_calendar(
        self,
        connection_id: str,
        calendar_id: str,
        *,
        update_calendar_request_calendar_id: typing.Optional[str] = OMIT,
        summary: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        timezone: typing.Optional[str] = OMIT,
        background_color: typing.Optional[str] = OMIT,
        foreground_color: typing.Optional[str] = OMIT,
        extra: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Optional[typing.Any]:
        """
        Parameters
        ----------
        connection_id : str

        calendar_id : str

        update_calendar_request_calendar_id : typing.Optional[str]

        summary : typing.Optional[str]

        description : typing.Optional[str]

        timezone : typing.Optional[str]

        background_color : typing.Optional[str]

        foreground_color : typing.Optional[str]

        extra : typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Optional[typing.Any]
            Successful Response

        Examples
        --------
        from omnidapter_sdk import OmnidapterApi

        client = OmnidapterApi(
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )
        client.calendar.update_calendar(
            connection_id="connection_id",
            calendar_id="calendar_id",
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/connections/{jsonable_encoder(connection_id)}/calendars/{jsonable_encoder(calendar_id)}",
            method="PATCH",
            json={
                "calendar_id": update_calendar_request_calendar_id,
                "summary": summary,
                "description": description,
                "timezone": timezone,
                "background_color": background_color,
                "foreground_color": foreground_color,
                "extra": extra,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    typing.Optional[typing.Any],
                    parse_obj_as(
                        type_=typing.Optional[typing.Any],  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def list_events(
        self,
        connection_id: str,
        calendar_id: str,
        *,
        start: typing.Optional[dt.datetime] = None,
        end: typing.Optional[dt.datetime] = None,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Optional[typing.Any]:
        """
        Parameters
        ----------
        connection_id : str

        calendar_id : str

        start : typing.Optional[dt.datetime]
            Filter events starting after this time (ISO 8601, e.g., 2026-04-06T10:00:00Z)

        end : typing.Optional[dt.datetime]
            Filter events ending before this time (ISO 8601, e.g., 2026-04-06T18:00:00Z)

        limit : typing.Optional[int]
            Maximum number of events to return per page

        offset : typing.Optional[int]
            Number of events to skip before returning results

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Optional[typing.Any]
            Successful Response

        Examples
        --------
        from omnidapter_sdk import OmnidapterApi

        client = OmnidapterApi(
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )
        client.calendar.list_events(
            connection_id="connection_id",
            calendar_id="calendar_id",
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/connections/{jsonable_encoder(connection_id)}/calendars/{jsonable_encoder(calendar_id)}/events",
            method="GET",
            params={
                "start": serialize_datetime(start) if start is not None else None,
                "end": serialize_datetime(end) if end is not None else None,
                "limit": limit,
                "offset": offset,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    typing.Optional[typing.Any],
                    parse_obj_as(
                        type_=typing.Optional[typing.Any],  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def create_event(
        self,
        connection_id: str,
        calendar_id: str,
        *,
        summary: str,
        start: CreateEventRequestStart,
        end: CreateEventRequestEnd,
        create_event_request_calendar_id: typing.Optional[str] = OMIT,
        all_day: typing.Optional[bool] = OMIT,
        timezone: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        location: typing.Optional[str] = OMIT,
        attendees: typing.Optional[typing.Sequence[Attendee]] = OMIT,
        recurrence: typing.Optional[Recurrence] = OMIT,
        conference_data: typing.Optional[ConferenceData] = OMIT,
        reminders: typing.Optional[Reminder] = OMIT,
        visibility: typing.Optional[str] = OMIT,
        status: typing.Optional[EventStatus] = OMIT,
        extra: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Optional[typing.Any]:
        """
        Parameters
        ----------
        connection_id : str

        calendar_id : str

        summary : str

        start : CreateEventRequestStart

        end : CreateEventRequestEnd

        create_event_request_calendar_id : typing.Optional[str]

        all_day : typing.Optional[bool]

        timezone : typing.Optional[str]

        description : typing.Optional[str]

        location : typing.Optional[str]

        attendees : typing.Optional[typing.Sequence[Attendee]]

        recurrence : typing.Optional[Recurrence]

        conference_data : typing.Optional[ConferenceData]

        reminders : typing.Optional[Reminder]

        visibility : typing.Optional[str]

        status : typing.Optional[EventStatus]

        extra : typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Optional[typing.Any]
            Successful Response

        Examples
        --------
        import datetime

        from omnidapter_sdk import OmnidapterApi

        client = OmnidapterApi(
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )
        client.calendar.create_event(
            connection_id="connection_id",
            calendar_id="calendar_id",
            summary="summary",
            start=datetime.datetime.fromisoformat(
                "2024-01-15 09:30:00+00:00",
            ),
            end=datetime.datetime.fromisoformat(
                "2024-01-15 09:30:00+00:00",
            ),
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/connections/{jsonable_encoder(connection_id)}/calendars/{jsonable_encoder(calendar_id)}/events",
            method="POST",
            json={
                "calendar_id": create_event_request_calendar_id,
                "summary": summary,
                "start": convert_and_respect_annotation_metadata(
                    object_=start, annotation=CreateEventRequestStart, direction="write"
                ),
                "end": convert_and_respect_annotation_metadata(
                    object_=end, annotation=CreateEventRequestEnd, direction="write"
                ),
                "all_day": all_day,
                "timezone": timezone,
                "description": description,
                "location": location,
                "attendees": convert_and_respect_annotation_metadata(
                    object_=attendees,
                    annotation=typing.Sequence[Attendee],
                    direction="write",
                ),
                "recurrence": convert_and_respect_annotation_metadata(
                    object_=recurrence,
                    annotation=typing.Optional[Recurrence],
                    direction="write",
                ),
                "conference_data": convert_and_respect_annotation_metadata(
                    object_=conference_data,
                    annotation=typing.Optional[ConferenceData],
                    direction="write",
                ),
                "reminders": convert_and_respect_annotation_metadata(
                    object_=reminders,
                    annotation=typing.Optional[Reminder],
                    direction="write",
                ),
                "visibility": visibility,
                "status": status,
                "extra": extra,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    typing.Optional[typing.Any],
                    parse_obj_as(
                        type_=typing.Optional[typing.Any],  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def get_event(
        self,
        connection_id: str,
        calendar_id: str,
        event_id: str,
        *,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Optional[typing.Any]:
        """
        Parameters
        ----------
        connection_id : str

        calendar_id : str

        event_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Optional[typing.Any]
            Successful Response

        Examples
        --------
        from omnidapter_sdk import OmnidapterApi

        client = OmnidapterApi(
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )
        client.calendar.get_event(
            connection_id="connection_id",
            calendar_id="calendar_id",
            event_id="event_id",
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/connections/{jsonable_encoder(connection_id)}/calendars/{jsonable_encoder(calendar_id)}/events/{jsonable_encoder(event_id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    typing.Optional[typing.Any],
                    parse_obj_as(
                        type_=typing.Optional[typing.Any],  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def delete_event(
        self,
        connection_id: str,
        calendar_id: str,
        event_id: str,
        *,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Parameters
        ----------
        connection_id : str

        calendar_id : str

        event_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from omnidapter_sdk import OmnidapterApi

        client = OmnidapterApi(
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )
        client.calendar.delete_event(
            connection_id="connection_id",
            calendar_id="calendar_id",
            event_id="event_id",
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/connections/{jsonable_encoder(connection_id)}/calendars/{jsonable_encoder(calendar_id)}/events/{jsonable_encoder(event_id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def update_event(
        self,
        connection_id: str,
        calendar_id: str,
        event_id: str,
        *,
        update_event_request_calendar_id: typing.Optional[str] = OMIT,
        update_event_request_event_id: typing.Optional[str] = OMIT,
        summary: typing.Optional[str] = OMIT,
        start: typing.Optional[UpdateEventRequestStart] = OMIT,
        end: typing.Optional[UpdateEventRequestEnd] = OMIT,
        all_day: typing.Optional[bool] = OMIT,
        timezone: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        location: typing.Optional[str] = OMIT,
        attendees: typing.Optional[typing.Sequence[Attendee]] = OMIT,
        recurrence: typing.Optional[Recurrence] = OMIT,
        conference_data: typing.Optional[ConferenceData] = OMIT,
        reminders: typing.Optional[Reminder] = OMIT,
        visibility: typing.Optional[str] = OMIT,
        status: typing.Optional[EventStatus] = OMIT,
        extra: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Optional[typing.Any]:
        """
        Parameters
        ----------
        connection_id : str

        calendar_id : str

        event_id : str

        update_event_request_calendar_id : typing.Optional[str]

        update_event_request_event_id : typing.Optional[str]

        summary : typing.Optional[str]

        start : typing.Optional[UpdateEventRequestStart]

        end : typing.Optional[UpdateEventRequestEnd]

        all_day : typing.Optional[bool]

        timezone : typing.Optional[str]

        description : typing.Optional[str]

        location : typing.Optional[str]

        attendees : typing.Optional[typing.Sequence[Attendee]]

        recurrence : typing.Optional[Recurrence]

        conference_data : typing.Optional[ConferenceData]

        reminders : typing.Optional[Reminder]

        visibility : typing.Optional[str]

        status : typing.Optional[EventStatus]

        extra : typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Optional[typing.Any]
            Successful Response

        Examples
        --------
        from omnidapter_sdk import OmnidapterApi

        client = OmnidapterApi(
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )
        client.calendar.update_event(
            connection_id="connection_id",
            calendar_id="calendar_id",
            event_id="event_id",
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/connections/{jsonable_encoder(connection_id)}/calendars/{jsonable_encoder(calendar_id)}/events/{jsonable_encoder(event_id)}",
            method="PATCH",
            json={
                "calendar_id": update_event_request_calendar_id,
                "event_id": update_event_request_event_id,
                "summary": summary,
                "start": convert_and_respect_annotation_metadata(
                    object_=start,
                    annotation=typing.Optional[UpdateEventRequestStart],
                    direction="write",
                ),
                "end": convert_and_respect_annotation_metadata(
                    object_=end,
                    annotation=typing.Optional[UpdateEventRequestEnd],
                    direction="write",
                ),
                "all_day": all_day,
                "timezone": timezone,
                "description": description,
                "location": location,
                "attendees": convert_and_respect_annotation_metadata(
                    object_=attendees,
                    annotation=typing.Optional[typing.Sequence[Attendee]],
                    direction="write",
                ),
                "recurrence": convert_and_respect_annotation_metadata(
                    object_=recurrence,
                    annotation=typing.Optional[Recurrence],
                    direction="write",
                ),
                "conference_data": convert_and_respect_annotation_metadata(
                    object_=conference_data,
                    annotation=typing.Optional[ConferenceData],
                    direction="write",
                ),
                "reminders": convert_and_respect_annotation_metadata(
                    object_=reminders,
                    annotation=typing.Optional[Reminder],
                    direction="write",
                ),
                "visibility": visibility,
                "status": status,
                "extra": extra,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    typing.Optional[typing.Any],
                    parse_obj_as(
                        type_=typing.Optional[typing.Any],  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def get_availability(
        self,
        connection_id: str,
        calendar_id: str,
        *,
        start: dt.datetime,
        end: dt.datetime,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Optional[typing.Any]:
        """
        Parameters
        ----------
        connection_id : str

        calendar_id : str

        start : dt.datetime

        end : dt.datetime

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Optional[typing.Any]
            Successful Response

        Examples
        --------
        import datetime

        from omnidapter_sdk import OmnidapterApi

        client = OmnidapterApi(
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )
        client.calendar.get_availability(
            connection_id="connection_id",
            calendar_id="calendar_id",
            start=datetime.datetime.fromisoformat(
                "2024-01-15 09:30:00+00:00",
            ),
            end=datetime.datetime.fromisoformat(
                "2024-01-15 09:30:00+00:00",
            ),
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/connections/{jsonable_encoder(connection_id)}/calendars/{jsonable_encoder(calendar_id)}/availability",
            method="GET",
            params={
                "start": serialize_datetime(start),
                "end": serialize_datetime(end),
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    typing.Optional[typing.Any],
                    parse_obj_as(
                        type_=typing.Optional[typing.Any],  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)


class AsyncCalendarClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def list_calendars(
        self,
        connection_id: str,
        *,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Optional[typing.Any]:
        """
        Parameters
        ----------
        connection_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Optional[typing.Any]
            Successful Response

        Examples
        --------
        import asyncio

        from omnidapter_sdk import AsyncOmnidapterApi

        client = AsyncOmnidapterApi(
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.calendar.list_calendars(
                connection_id="connection_id",
            )


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/connections/{jsonable_encoder(connection_id)}/calendars",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    typing.Optional[typing.Any],
                    parse_obj_as(
                        type_=typing.Optional[typing.Any],  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def create_calendar(
        self,
        connection_id: str,
        *,
        summary: str,
        description: typing.Optional[str] = OMIT,
        timezone: typing.Optional[str] = OMIT,
        background_color: typing.Optional[str] = OMIT,
        foreground_color: typing.Optional[str] = OMIT,
        extra: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Optional[typing.Any]:
        """
        Parameters
        ----------
        connection_id : str

        summary : str

        description : typing.Optional[str]

        timezone : typing.Optional[str]

        background_color : typing.Optional[str]

        foreground_color : typing.Optional[str]

        extra : typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Optional[typing.Any]
            Successful Response

        Examples
        --------
        import asyncio

        from omnidapter_sdk import AsyncOmnidapterApi

        client = AsyncOmnidapterApi(
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.calendar.create_calendar(
                connection_id="connection_id",
                summary="summary",
            )


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/connections/{jsonable_encoder(connection_id)}/calendars",
            method="POST",
            json={
                "summary": summary,
                "description": description,
                "timezone": timezone,
                "background_color": background_color,
                "foreground_color": foreground_color,
                "extra": extra,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    typing.Optional[typing.Any],
                    parse_obj_as(
                        type_=typing.Optional[typing.Any],  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def get_calendar(
        self,
        connection_id: str,
        calendar_id: str,
        *,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Optional[typing.Any]:
        """
        Parameters
        ----------
        connection_id : str

        calendar_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Optional[typing.Any]
            Successful Response

        Examples
        --------
        import asyncio

        from omnidapter_sdk import AsyncOmnidapterApi

        client = AsyncOmnidapterApi(
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.calendar.get_calendar(
                connection_id="connection_id",
                calendar_id="calendar_id",
            )


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/connections/{jsonable_encoder(connection_id)}/calendars/{jsonable_encoder(calendar_id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    typing.Optional[typing.Any],
                    parse_obj_as(
                        type_=typing.Optional[typing.Any],  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def delete_calendar(
        self,
        connection_id: str,
        calendar_id: str,
        *,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Parameters
        ----------
        connection_id : str

        calendar_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from omnidapter_sdk import AsyncOmnidapterApi

        client = AsyncOmnidapterApi(
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.calendar.delete_calendar(
                connection_id="connection_id",
                calendar_id="calendar_id",
            )


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/connections/{jsonable_encoder(connection_id)}/calendars/{jsonable_encoder(calendar_id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def update_calendar(
        self,
        connection_id: str,
        calendar_id: str,
        *,
        update_calendar_request_calendar_id: typing.Optional[str] = OMIT,
        summary: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        timezone: typing.Optional[str] = OMIT,
        background_color: typing.Optional[str] = OMIT,
        foreground_color: typing.Optional[str] = OMIT,
        extra: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Optional[typing.Any]:
        """
        Parameters
        ----------
        connection_id : str

        calendar_id : str

        update_calendar_request_calendar_id : typing.Optional[str]

        summary : typing.Optional[str]

        description : typing.Optional[str]

        timezone : typing.Optional[str]

        background_color : typing.Optional[str]

        foreground_color : typing.Optional[str]

        extra : typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Optional[typing.Any]
            Successful Response

        Examples
        --------
        import asyncio

        from omnidapter_sdk import AsyncOmnidapterApi

        client = AsyncOmnidapterApi(
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.calendar.update_calendar(
                connection_id="connection_id",
                calendar_id="calendar_id",
            )


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/connections/{jsonable_encoder(connection_id)}/calendars/{jsonable_encoder(calendar_id)}",
            method="PATCH",
            json={
                "calendar_id": update_calendar_request_calendar_id,
                "summary": summary,
                "description": description,
                "timezone": timezone,
                "background_color": background_color,
                "foreground_color": foreground_color,
                "extra": extra,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    typing.Optional[typing.Any],
                    parse_obj_as(
                        type_=typing.Optional[typing.Any],  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def list_events(
        self,
        connection_id: str,
        calendar_id: str,
        *,
        start: typing.Optional[dt.datetime] = None,
        end: typing.Optional[dt.datetime] = None,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Optional[typing.Any]:
        """
        Parameters
        ----------
        connection_id : str

        calendar_id : str

        start : typing.Optional[dt.datetime]
            Filter events starting after this time (ISO 8601, e.g., 2026-04-06T10:00:00Z)

        end : typing.Optional[dt.datetime]
            Filter events ending before this time (ISO 8601, e.g., 2026-04-06T18:00:00Z)

        limit : typing.Optional[int]
            Maximum number of events to return per page

        offset : typing.Optional[int]
            Number of events to skip before returning results

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Optional[typing.Any]
            Successful Response

        Examples
        --------
        import asyncio

        from omnidapter_sdk import AsyncOmnidapterApi

        client = AsyncOmnidapterApi(
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.calendar.list_events(
                connection_id="connection_id",
                calendar_id="calendar_id",
            )


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/connections/{jsonable_encoder(connection_id)}/calendars/{jsonable_encoder(calendar_id)}/events",
            method="GET",
            params={
                "start": serialize_datetime(start) if start is not None else None,
                "end": serialize_datetime(end) if end is not None else None,
                "limit": limit,
                "offset": offset,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    typing.Optional[typing.Any],
                    parse_obj_as(
                        type_=typing.Optional[typing.Any],  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def create_event(
        self,
        connection_id: str,
        calendar_id: str,
        *,
        summary: str,
        start: CreateEventRequestStart,
        end: CreateEventRequestEnd,
        create_event_request_calendar_id: typing.Optional[str] = OMIT,
        all_day: typing.Optional[bool] = OMIT,
        timezone: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        location: typing.Optional[str] = OMIT,
        attendees: typing.Optional[typing.Sequence[Attendee]] = OMIT,
        recurrence: typing.Optional[Recurrence] = OMIT,
        conference_data: typing.Optional[ConferenceData] = OMIT,
        reminders: typing.Optional[Reminder] = OMIT,
        visibility: typing.Optional[str] = OMIT,
        status: typing.Optional[EventStatus] = OMIT,
        extra: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Optional[typing.Any]:
        """
        Parameters
        ----------
        connection_id : str

        calendar_id : str

        summary : str

        start : CreateEventRequestStart

        end : CreateEventRequestEnd

        create_event_request_calendar_id : typing.Optional[str]

        all_day : typing.Optional[bool]

        timezone : typing.Optional[str]

        description : typing.Optional[str]

        location : typing.Optional[str]

        attendees : typing.Optional[typing.Sequence[Attendee]]

        recurrence : typing.Optional[Recurrence]

        conference_data : typing.Optional[ConferenceData]

        reminders : typing.Optional[Reminder]

        visibility : typing.Optional[str]

        status : typing.Optional[EventStatus]

        extra : typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Optional[typing.Any]
            Successful Response

        Examples
        --------
        import asyncio
        import datetime

        from omnidapter_sdk import AsyncOmnidapterApi

        client = AsyncOmnidapterApi(
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.calendar.create_event(
                connection_id="connection_id",
                calendar_id="calendar_id",
                summary="summary",
                start=datetime.datetime.fromisoformat(
                    "2024-01-15 09:30:00+00:00",
                ),
                end=datetime.datetime.fromisoformat(
                    "2024-01-15 09:30:00+00:00",
                ),
            )


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/connections/{jsonable_encoder(connection_id)}/calendars/{jsonable_encoder(calendar_id)}/events",
            method="POST",
            json={
                "calendar_id": create_event_request_calendar_id,
                "summary": summary,
                "start": convert_and_respect_annotation_metadata(
                    object_=start, annotation=CreateEventRequestStart, direction="write"
                ),
                "end": convert_and_respect_annotation_metadata(
                    object_=end, annotation=CreateEventRequestEnd, direction="write"
                ),
                "all_day": all_day,
                "timezone": timezone,
                "description": description,
                "location": location,
                "attendees": convert_and_respect_annotation_metadata(
                    object_=attendees,
                    annotation=typing.Sequence[Attendee],
                    direction="write",
                ),
                "recurrence": convert_and_respect_annotation_metadata(
                    object_=recurrence,
                    annotation=typing.Optional[Recurrence],
                    direction="write",
                ),
                "conference_data": convert_and_respect_annotation_metadata(
                    object_=conference_data,
                    annotation=typing.Optional[ConferenceData],
                    direction="write",
                ),
                "reminders": convert_and_respect_annotation_metadata(
                    object_=reminders,
                    annotation=typing.Optional[Reminder],
                    direction="write",
                ),
                "visibility": visibility,
                "status": status,
                "extra": extra,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    typing.Optional[typing.Any],
                    parse_obj_as(
                        type_=typing.Optional[typing.Any],  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def get_event(
        self,
        connection_id: str,
        calendar_id: str,
        event_id: str,
        *,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Optional[typing.Any]:
        """
        Parameters
        ----------
        connection_id : str

        calendar_id : str

        event_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Optional[typing.Any]
            Successful Response

        Examples
        --------
        import asyncio

        from omnidapter_sdk import AsyncOmnidapterApi

        client = AsyncOmnidapterApi(
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.calendar.get_event(
                connection_id="connection_id",
                calendar_id="calendar_id",
                event_id="event_id",
            )


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/connections/{jsonable_encoder(connection_id)}/calendars/{jsonable_encoder(calendar_id)}/events/{jsonable_encoder(event_id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    typing.Optional[typing.Any],
                    parse_obj_as(
                        type_=typing.Optional[typing.Any],  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def delete_event(
        self,
        connection_id: str,
        calendar_id: str,
        event_id: str,
        *,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Parameters
        ----------
        connection_id : str

        calendar_id : str

        event_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from omnidapter_sdk import AsyncOmnidapterApi

        client = AsyncOmnidapterApi(
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.calendar.delete_event(
                connection_id="connection_id",
                calendar_id="calendar_id",
                event_id="event_id",
            )


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/connections/{jsonable_encoder(connection_id)}/calendars/{jsonable_encoder(calendar_id)}/events/{jsonable_encoder(event_id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def update_event(
        self,
        connection_id: str,
        calendar_id: str,
        event_id: str,
        *,
        update_event_request_calendar_id: typing.Optional[str] = OMIT,
        update_event_request_event_id: typing.Optional[str] = OMIT,
        summary: typing.Optional[str] = OMIT,
        start: typing.Optional[UpdateEventRequestStart] = OMIT,
        end: typing.Optional[UpdateEventRequestEnd] = OMIT,
        all_day: typing.Optional[bool] = OMIT,
        timezone: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        location: typing.Optional[str] = OMIT,
        attendees: typing.Optional[typing.Sequence[Attendee]] = OMIT,
        recurrence: typing.Optional[Recurrence] = OMIT,
        conference_data: typing.Optional[ConferenceData] = OMIT,
        reminders: typing.Optional[Reminder] = OMIT,
        visibility: typing.Optional[str] = OMIT,
        status: typing.Optional[EventStatus] = OMIT,
        extra: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Optional[typing.Any]:
        """
        Parameters
        ----------
        connection_id : str

        calendar_id : str

        event_id : str

        update_event_request_calendar_id : typing.Optional[str]

        update_event_request_event_id : typing.Optional[str]

        summary : typing.Optional[str]

        start : typing.Optional[UpdateEventRequestStart]

        end : typing.Optional[UpdateEventRequestEnd]

        all_day : typing.Optional[bool]

        timezone : typing.Optional[str]

        description : typing.Optional[str]

        location : typing.Optional[str]

        attendees : typing.Optional[typing.Sequence[Attendee]]

        recurrence : typing.Optional[Recurrence]

        conference_data : typing.Optional[ConferenceData]

        reminders : typing.Optional[Reminder]

        visibility : typing.Optional[str]

        status : typing.Optional[EventStatus]

        extra : typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Optional[typing.Any]
            Successful Response

        Examples
        --------
        import asyncio

        from omnidapter_sdk import AsyncOmnidapterApi

        client = AsyncOmnidapterApi(
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.calendar.update_event(
                connection_id="connection_id",
                calendar_id="calendar_id",
                event_id="event_id",
            )


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/connections/{jsonable_encoder(connection_id)}/calendars/{jsonable_encoder(calendar_id)}/events/{jsonable_encoder(event_id)}",
            method="PATCH",
            json={
                "calendar_id": update_event_request_calendar_id,
                "event_id": update_event_request_event_id,
                "summary": summary,
                "start": convert_and_respect_annotation_metadata(
                    object_=start,
                    annotation=typing.Optional[UpdateEventRequestStart],
                    direction="write",
                ),
                "end": convert_and_respect_annotation_metadata(
                    object_=end,
                    annotation=typing.Optional[UpdateEventRequestEnd],
                    direction="write",
                ),
                "all_day": all_day,
                "timezone": timezone,
                "description": description,
                "location": location,
                "attendees": convert_and_respect_annotation_metadata(
                    object_=attendees,
                    annotation=typing.Optional[typing.Sequence[Attendee]],
                    direction="write",
                ),
                "recurrence": convert_and_respect_annotation_metadata(
                    object_=recurrence,
                    annotation=typing.Optional[Recurrence],
                    direction="write",
                ),
                "conference_data": convert_and_respect_annotation_metadata(
                    object_=conference_data,
                    annotation=typing.Optional[ConferenceData],
                    direction="write",
                ),
                "reminders": convert_and_respect_annotation_metadata(
                    object_=reminders,
                    annotation=typing.Optional[Reminder],
                    direction="write",
                ),
                "visibility": visibility,
                "status": status,
                "extra": extra,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    typing.Optional[typing.Any],
                    parse_obj_as(
                        type_=typing.Optional[typing.Any],  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def get_availability(
        self,
        connection_id: str,
        calendar_id: str,
        *,
        start: dt.datetime,
        end: dt.datetime,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Optional[typing.Any]:
        """
        Parameters
        ----------
        connection_id : str

        calendar_id : str

        start : dt.datetime

        end : dt.datetime

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Optional[typing.Any]
            Successful Response

        Examples
        --------
        import asyncio
        import datetime

        from omnidapter_sdk import AsyncOmnidapterApi

        client = AsyncOmnidapterApi(
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.calendar.get_availability(
                connection_id="connection_id",
                calendar_id="calendar_id",
                start=datetime.datetime.fromisoformat(
                    "2024-01-15 09:30:00+00:00",
                ),
                end=datetime.datetime.fromisoformat(
                    "2024-01-15 09:30:00+00:00",
                ),
            )


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/connections/{jsonable_encoder(connection_id)}/calendars/{jsonable_encoder(calendar_id)}/availability",
            method="GET",
            params={
                "start": serialize_datetime(start),
                "end": serialize_datetime(end),
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    typing.Optional[typing.Any],
                    parse_obj_as(
                        type_=typing.Optional[typing.Any],  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)
