name: CI
run-name: CI — ${{ github.event.pull_request.title || github.ref_name }}

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test-python:
    uses: ./.github/workflows/_test-python.yml

  test-sdk:
    if: github.event_name == 'push'
    uses: ./.github/workflows/_test-sdk.yml
